const fs = require('fs');
const path = require('path');
const { createRecipe } = require('./recipeHelper.cjs');

const soups = [
  createRecipe({
    id: "rec_cor_01",
    code: "REC-COR-001",
    name: "Mercimek Çorbası (Geleneksel)",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 40,
    calorie: 165,
    protein: 7.5,
    carb: 22.0,
    fat: 4.8,
    allergens: ["Gluten (Un)", "Laktoz (Tereyağı)"],
    instructions: "Kırmızı mercimek, soğan, havuç ve patates et suyuyla yumuşayana kadar haşlanır. Blenderdan geçirilip tereyağlı un ve nane meyanesi eklenir.",
    labor: 2.2, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_01_1", name: "Kırmızı Mercimek", portionGrams: 45, unit: "g", unitCost: 45, portionCost: 2.03, wastagePercent: 0 },
      { id: "ing_cor_01_2", name: "Kuru Soğan", portionGrams: 25, unit: "g", unitCost: 18, portionCost: 0.45, wastagePercent: 10 },
      { id: "ing_cor_01_3", name: "Havuç & Patates", portionGrams: 30, unit: "g", unitCost: 25, portionCost: 0.75, wastagePercent: 12 },
      { id: "ing_cor_01_4", name: "Mutfak Tereyağı & Sıvı Yağ", portionGrams: 12, unit: "g", unitCost: 220, portionCost: 2.64, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_01_5", name: "Kemik Suyu", portionGrams: 100, unit: "ml", unitCost: 40, portionCost: 4.0, wastagePercent: 0 },
      { id: "ing_cor_01_6", name: "Baharat (Nane, Pul Biber, Kimyon)", portionGrams: 4, unit: "g", unitCost: 80, portionCost: 0.32, wastagePercent: 0 },
    ]
  }),
  createRecipe({
    id: "rec_cor_02",
    code: "REC-COR-002",
    name: "Sarı Mercimek Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 40,
    calorie: 170,
    protein: 8.0,
    carb: 23.0,
    fat: 5.0,
    allergens: ["Laktoz (Tereyağı)"],
    instructions: "Sarı mercimek, arpacık soğan ve patates tavuk suyuyla pişirilir. Zerdeçal ve tereyağlı sos ile pürüzsüz servis edilir.",
    labor: 2.2, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_02_1", name: "Sarı Mercimek", portionGrams: 50, unit: "g", unitCost: 55, portionCost: 2.75, wastagePercent: 0 },
      { id: "ing_cor_02_2", name: "Kuru Soğan & Patates", portionGrams: 40, unit: "g", unitCost: 22, portionCost: 0.88, wastagePercent: 10 },
      { id: "ing_cor_02_3", name: "Tavuk Suyu", portionGrams: 100, unit: "ml", unitCost: 35, portionCost: 3.5, wastagePercent: 0 },
      { id: "ing_cor_02_4", name: "Tereyağı & Zerdeçal", portionGrams: 12, unit: "g", unitCost: 250, portionCost: 3.0, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_02_5", name: "Kaya Tuzu & Beyaz Biber", portionGrams: 3, unit: "g", unitCost: 60, portionCost: 0.18, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_03",
    code: "REC-COR-003",
    name: "Ezogelin Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 45,
    calorie: 175,
    protein: 6.8,
    carb: 26.0,
    fat: 5.2,
    allergens: ["Gluten (Bulgur)", "Laktoz (Tereyağı)"],
    instructions: "Kırmızı mercimek, pilavlık bulgur ve pirinç soğan ve salçayla kavrulup et suyuyla pişirilir, bol nane ve acı pul biber ile harmanlanır.",
    labor: 2.3, gas: 1.4, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_03_1", name: "Kırmızı Mercimek", portionGrams: 35, unit: "g", unitCost: 45, portionCost: 1.58, wastagePercent: 0 },
      { id: "ing_cor_03_2", name: "Pilavlık Bulgur & Pirinç", portionGrams: 20, unit: "g", unitCost: 40, portionCost: 0.8, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_03_3", name: "Domates & Biber Salçası", portionGrams: 15, unit: "g", unitCost: 85, portionCost: 1.28, wastagePercent: 0 },
      { id: "ing_cor_03_4", name: "Kuru Soğan & Sarımsak", portionGrams: 25, unit: "g", unitCost: 22, portionCost: 0.55, wastagePercent: 10 },
      { id: "ing_cor_03_5", name: "Tereyağı & Sıvı Yağ", portionGrams: 12, unit: "g", unitCost: 220, portionCost: 2.64, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_03_6", name: "Kuru Nane & Pul Biber", portionGrams: 5, unit: "g", unitCost: 85, portionCost: 0.43, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_04",
    code: "REC-COR-004",
    name: "Yayla Çorbası (Yoğurt Çorbası)",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 30,
    calorie: 155,
    protein: 5.5,
    carb: 19.0,
    fat: 6.5,
    allergens: ["Laktoz (Yoğurt, Tereyağı)", "Yumurta", "Gluten (Un)"],
    instructions: "Pirinç suda yumuşayana kadar haşlanır. Süzme yoğurt, yumurta sarısı ve unla çırpılan terbiye kesilmemesi için ılıklaştırılarak çorbaya ilave edilir. Üzerine tereyağlı nane yakılır.",
    labor: 2.3, gas: 1.1, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_04_1", name: "Süzme & Yağlı Yoğurt", portionGrams: 70, unit: "g", unitCost: 65, portionCost: 4.55, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_04_2", name: "Kırık Pirinç", portionGrams: 20, unit: "g", unitCost: 50, portionCost: 1.0, wastagePercent: 0 },
      { id: "ing_cor_04_3", name: "Yumurta Sarısı & Un", portionGrams: 15, unit: "g", unitCost: 70, portionCost: 1.05, wastagePercent: 0, allergen: "Yumurta, Gluten" },
      { id: "ing_cor_04_4", name: "Mutfak Tereyağı", portionGrams: 10, unit: "g", unitCost: 320, portionCost: 3.2, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_04_5", name: "Kuru Nane & Tuz", portionGrams: 4, unit: "g", unitCost: 75, portionCost: 0.3, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_05",
    code: "REC-COR-005",
    name: "Tarhana Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 10,
    cookTime: 25,
    calorie: 140,
    protein: 5.0,
    carb: 21.0,
    fat: 4.2,
    allergens: ["Gluten (Tarhana)", "Laktoz (Yoğurtlu Tarhana)"],
    instructions: "Geleneksel ev tarhanası ılık suyla ıslatılır. Salça ve sarımsak tereyağında kokusu çıkana kadar sotelenip tarhana suyu eklenir ve sürekli karıştırılarak kaynatılır.",
    labor: 2.0, gas: 1.0, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_05_1", name: "Köy Usulü Ev Tarhanası", portionGrams: 35, unit: "g", unitCost: 110, portionCost: 3.85, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_05_2", name: "Domates Salçası", portionGrams: 12, unit: "g", unitCost: 85, portionCost: 1.02, wastagePercent: 0 },
      { id: "ing_cor_05_3", name: "Mutfak Tereyağı & Sıvı Yağ", portionGrams: 10, unit: "g", unitCost: 220, portionCost: 2.2, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_05_4", name: "Sarımsak & Nane", portionGrams: 6, unit: "g", unitCost: 60, portionCost: 0.36, wastagePercent: 0 },
      { id: "ing_cor_05_5", name: "Kemik Suyu / Su", portionGrams: 120, unit: "ml", unitCost: 25, portionCost: 3.0, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_06",
    code: "REC-COR-006",
    name: "Uşak Tarhanası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 10,
    cookTime: 30,
    calorie: 150,
    protein: 5.2,
    carb: 22.5,
    fat: 4.8,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Coğrafi işaretli Uşak tarhanası, tereyağı, domates-biber püresi ve kıyılmış kuru nane ile kısık ateşte pişirilir.",
    labor: 2.1, gas: 1.1, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_06_1", name: "Uşak Coğrafi İşaretli Tarhana", portionGrams: 38, unit: "g", unitCost: 135, portionCost: 5.13, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_06_2", name: "Köy Tereyağı", portionGrams: 12, unit: "g", unitCost: 320, portionCost: 3.84, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_06_3", name: "Taze Sarımsak & Biber Salçası", portionGrams: 10, unit: "g", unitCost: 80, portionCost: 0.8, wastagePercent: 0 },
      { id: "ing_cor_06_4", name: "Et Suyu", portionGrams: 100, unit: "ml", unitCost: 35, portionCost: 3.5, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_07",
    code: "REC-COR-007",
    name: "İşkembe Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 30,
    cookTime: 120,
    calorie: 240,
    protein: 18.5,
    carb: 9.0,
    fat: 14.5,
    allergens: ["Yumurta", "Gluten (Un)", "Laktoz (Yoğurt/Tereyağı)"],
    instructions: "Temizlenmiş dana işkembe düdüklüde lokum gibi haşlanır. Küçük küp doğranır. Un, yoğurt, yumurta sarısı ve limon suyu terbiyesi eklenir. Sarımsaklı sirke sosu ile servis edilir.",
    labor: 4.5, gas: 3.5, overhead: 1.2,
    ingredients: [
      { id: "ing_cor_07_1", name: "Temizlenmiş Dana İşkembe", portionGrams: 90, unit: "g", unitCost: 220, portionCost: 19.8, wastagePercent: 15 },
      { id: "ing_cor_07_2", name: "İşkembe Haşlama Suyu", portionGrams: 120, unit: "ml", unitCost: 20, portionCost: 2.4, wastagePercent: 0 },
      { id: "ing_cor_07_3", name: "Yoğurt & Yumurta Terbiyesi", portionGrams: 25, unit: "g", unitCost: 80, portionCost: 2.0, wastagePercent: 0, allergen: "Laktoz, Yumurta" },
      { id: "ing_cor_07_4", name: "Un & Tereyağı", portionGrams: 15, unit: "g", unitCost: 180, portionCost: 2.7, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_07_5", name: "Sarımsak, Sirke & Pul Biber", portionGrams: 15, unit: "g", unitCost: 60, portionCost: 0.9, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_08",
    code: "REC-COR-008",
    name: "Kelle Paça Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 30,
    cookTime: 150,
    calorie: 280,
    protein: 22.0,
    carb: 6.0,
    fat: 18.0,
    allergens: ["Gluten (Un)", "Laktoz (Tereyağı)", "Yumurta"],
    instructions: "Uzun süre kaynatılan kuzu kelle ve paça etleri tiftiklenir. Zengin kolajenli et suyu, un-yumurta-limon terbiyesi ve kızgın biberli tereyağı ile taçlandırılır.",
    labor: 5.0, gas: 4.0, overhead: 1.2,
    ingredients: [
      { id: "ing_cor_08_1", name: "Kuzu Kelle & Gerdan Eti", portionGrams: 85, unit: "g", unitCost: 380, portionCost: 32.3, wastagePercent: 20 },
      { id: "ing_cor_08_2", name: "Doğal Kolajenli Kelle Suyu", portionGrams: 130, unit: "ml", unitCost: 35, portionCost: 4.55, wastagePercent: 0 },
      { id: "ing_cor_08_3", name: "Yumurta & Limon Terbiyesi", portionGrams: 20, unit: "g", unitCost: 80, portionCost: 1.6, wastagePercent: 0, allergen: "Yumurta" },
      { id: "ing_cor_08_4", name: "Sarımsaklı Sirke Çeşnisi", portionGrams: 15, unit: "ml", unitCost: 50, portionCost: 0.75, wastagePercent: 0 },
      { id: "ing_cor_08_5", name: "Mutfak Tereyağı & Pul Biber", portionGrams: 10, unit: "g", unitCost: 320, portionCost: 3.2, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_09",
    code: "REC-COR-009",
    name: "Ayak Paça Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 25,
    cookTime: 140,
    calorie: 260,
    protein: 20.0,
    carb: 5.0,
    fat: 17.5,
    allergens: ["Yumurta", "Gluten", "Laktoz"],
    instructions: "Dana ve kuzu ayakları ilikli suyunu bırakana kadar pişirilir. Ayak etleri ayıklanıp un-yumurta terbiyeli kolajen çorbasına katılır.",
    labor: 4.8, gas: 3.8, overhead: 1.1,
    ingredients: [
      { id: "ing_cor_09_1", name: "Haşlanmış Paça / Ayak Eti", portionGrams: 80, unit: "g", unitCost: 260, portionCost: 20.8, wastagePercent: 20 },
      { id: "ing_cor_09_2", name: "Ayak Paça Kolajen Suyu", portionGrams: 130, unit: "ml", unitCost: 30, portionCost: 3.9, wastagePercent: 0 },
      { id: "ing_cor_09_3", name: "Un, Yumurta & Yoğurt Terbiyesi", portionGrams: 25, unit: "g", unitCost: 75, portionCost: 1.88, wastagePercent: 0, allergen: "Gluten, Yumurta, Laktoz" },
      { id: "ing_cor_09_4", name: "Sarımsak & Üzüm Sirkesi", portionGrams: 15, unit: "ml", unitCost: 50, portionCost: 0.75, wastagePercent: 0 },
      { id: "ing_cor_09_5", name: "Tereyağı & Kırmızı Biber", portionGrams: 10, unit: "g", unitCost: 320, portionCost: 3.2, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_10",
    code: "REC-COR-010",
    name: "Tuzlama Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 25,
    cookTime: 110,
    calorie: 250,
    protein: 19.0,
    carb: 7.0,
    fat: 16.0,
    allergens: ["Gluten", "Laktoz", "Yumurta"],
    instructions: "İşkembenin en etli ve kalın tuzlama kısmı iri parçalar halinde doğranarak terbiyeli et suyu ile hazırlanır.",
    labor: 4.5, gas: 3.2, overhead: 1.0,
    ingredients: [
      { id: "ing_cor_10_1", name: "Dana İşkembe (Tuzlama Parça)", portionGrams: 95, unit: "g", unitCost: 240, portionCost: 22.8, wastagePercent: 12 },
      { id: "ing_cor_10_2", name: "İşkembe & Kemik Suyu", portionGrams: 120, unit: "ml", unitCost: 25, portionCost: 3.0, wastagePercent: 0 },
      { id: "ing_cor_10_3", name: "Un & Yumurta Terbiyesi", portionGrams: 20, unit: "g", unitCost: 75, portionCost: 1.5, wastagePercent: 0, allergen: "Gluten, Yumurta" },
      { id: "ing_cor_10_4", name: "Kızgın Tereyağı & Toz Kırmızı Biber", portionGrams: 12, unit: "g", unitCost: 280, portionCost: 3.36, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_10_5", name: "Dövme Sarımsak & Sirke", portionGrams: 15, unit: "g", unitCost: 50, portionCost: 0.75, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_11",
    code: "REC-COR-011",
    name: "Şirden Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 30,
    cookTime: 120,
    calorie: 235,
    protein: 17.5,
    carb: 8.0,
    fat: 14.5,
    allergens: ["Gluten", "Laktoz", "Yumurta"],
    instructions: "Geleneksel şirden sakatatı iyice temizlenip baharatlı et suyunda haşlanır, ince dilimlenip terbiyeli çorba suyu ile sunulur.",
    labor: 4.6, gas: 3.5, overhead: 1.0,
    ingredients: [
      { id: "ing_cor_11_1", name: "Temizlenmiş Kuzu Şirden", portionGrams: 85, unit: "g", unitCost: 230, portionCost: 19.55, wastagePercent: 15 },
      { id: "ing_cor_11_2", name: "Özel Kemik Suyu", portionGrams: 120, unit: "ml", unitCost: 25, portionCost: 3.0, wastagePercent: 0 },
      { id: "ing_cor_11_3", name: "Terbiye (Un, Yoğurt, Yumurta)", portionGrams: 20, unit: "g", unitCost: 75, portionCost: 1.5, wastagePercent: 0, allergen: "Gluten, Laktoz, Yumurta" },
      { id: "ing_cor_11_4", name: "Tereyağı & Pul Biber", portionGrams: 10, unit: "g", unitCost: 320, portionCost: 3.2, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_12",
    code: "REC-COR-012",
    name: "Domates Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 35,
    calorie: 145,
    protein: 4.5,
    carb: 18.0,
    fat: 6.0,
    allergens: ["Gluten (Un)", "Laktoz (Süt, Kaşar)"],
    instructions: "Tereyağında un kavrulur. Salça ve taze domates rendesi eklenip et suyu ve ılık süt ilavesiyle pürüzsüz kıvama getirilir. Üzerine rendelenmiş kaşar peyniri serpilir.",
    labor: 2.2, gas: 1.2, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_12_1", name: "Salçalık Domates Rendesi", portionGrams: 80, unit: "g", unitCost: 30, portionCost: 2.4, wastagePercent: 5 },
      { id: "ing_cor_12_2", name: "Un & Mutfak Tereyağı", portionGrams: 18, unit: "g", unitCost: 200, portionCost: 3.6, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_12_3", name: "Tam Yağlı Süt & Et Suyu", portionGrams: 100, unit: "ml", unitCost: 35, portionCost: 3.5, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_12_4", name: "Rendelenmiş Taze Kaşar", portionGrams: 15, unit: "g", unitCost: 260, portionCost: 3.9, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_12_5", name: "Tuz & Karabiber", portionGrams: 3, unit: "g", unitCost: 60, portionCost: 0.18, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_13",
    code: "REC-COR-013",
    name: "Köz Domates Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 20,
    cookTime: 40,
    calorie: 155,
    protein: 4.8,
    carb: 18.5,
    fat: 6.8,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Fırında közlenen salkım domates, sarımsak ve kapya biber kabukları soyularak tereyağlı meyane ile çekilir, fesleğen ve kaşar rendesiyle servis edilir.",
    labor: 2.4, gas: 1.5, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_13_1", name: "Közlenmiş Salkım Domates", portionGrams: 90, unit: "g", unitCost: 35, portionCost: 3.15, wastagePercent: 15 },
      { id: "ing_cor_13_2", name: "Köz Kapya Biber & Sarımsak", portionGrams: 30, unit: "g", unitCost: 40, portionCost: 1.2, wastagePercent: 10 },
      { id: "ing_cor_13_3", name: "Tereyağı & Un", portionGrams: 16, unit: "g", unitCost: 220, portionCost: 3.52, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_13_4", name: "Süt & Tavuk Suyu", portionGrams: 100, unit: "ml", unitCost: 35, portionCost: 3.5, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_13_5", name: "Taze Fesleğen & Kaşar", portionGrams: 15, unit: "g", unitCost: 260, portionCost: 3.9, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_14",
    code: "REC-COR-014",
    name: "Düğün Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 25,
    cookTime: 80,
    calorie: 220,
    protein: 15.0,
    carb: 12.0,
    fat: 12.5,
    allergens: ["Gluten (Un)", "Laktoz (Yoğurt, Tereyağı)", "Yumurta"],
    instructions: "Kuzu gerdan eti ilikli suyunda haşlanıp tel tel didiklenir. Un, yoğurt ve yumurta sarısıyla hazırlanan terbiye bağlanır. Üzerine kızdırılmış kırmızı biberli tereyağı gezdirilir.",
    labor: 3.5, gas: 2.5, overhead: 0.8,
    ingredients: [
      { id: "ing_cor_14_1", name: "Kuzu Gerdan Eti (Didiklenmiş)", portionGrams: 55, unit: "g", unitCost: 420, portionCost: 23.1, wastagePercent: 20 },
      { id: "ing_cor_14_2", name: "İlikli Kuzu Gerdan Suyu", portionGrams: 130, unit: "ml", unitCost: 35, portionCost: 4.55, wastagePercent: 0 },
      { id: "ing_cor_14_3", name: "Süzme Yoğurt & Un Terbiyesi", portionGrams: 25, unit: "g", unitCost: 75, portionCost: 1.88, wastagePercent: 0, allergen: "Laktoz, Gluten" },
      { id: "ing_cor_14_4", name: "Yumurta Sarısı & Limon", portionGrams: 15, unit: "g", unitCost: 80, portionCost: 1.2, wastagePercent: 0, allergen: "Yumurta" },
      { id: "ing_cor_14_5", name: "Tereyağı & Pul Biber", portionGrams: 12, unit: "g", unitCost: 320, portionCost: 3.84, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_15",
    code: "REC-COR-015",
    name: "Beyran Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 270,
    prepTime: 30,
    cookTime: 120,
    calorie: 310,
    protein: 23.0,
    carb: 18.0,
    fat: 16.5,
    allergens: [],
    instructions: "Gaziantep usulü bakır sahanda iç yağı eritilir, haşlanmış pirinç, bol liflenmiş kuzu eti, sarımsak, pul biber ve kaynayan et suyu eklenip harlı ateşte kaynatılır.",
    labor: 4.5, gas: 3.5, overhead: 1.2,
    ingredients: [
      { id: "ing_cor_15_1", name: "Kuzu Gerdan / Küşleme Eti (Didik)", portionGrams: 75, unit: "g", unitCost: 450, portionCost: 33.75, wastagePercent: 20 },
      { id: "ing_cor_15_2", name: "Haşlanmış Baldo Pirinç", portionGrams: 25, unit: "g", unitCost: 80, portionCost: 2.0, wastagePercent: 0 },
      { id: "ing_cor_15_3", name: "İlikli Kuzu Et Suyu", portionGrams: 130, unit: "ml", unitCost: 40, portionCost: 5.2, wastagePercent: 0 },
      { id: "ing_cor_15_4", name: "Kuzu İç Yağı / Kavrulmuş Yağ", portionGrams: 15, unit: "g", unitCost: 180, portionCost: 2.7, wastagePercent: 0 },
      { id: "ing_cor_15_5", name: "Bol Sarımsak & Antep İpek Pul Biber", portionGrams: 12, unit: "g", unitCost: 90, portionCost: 1.08, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_16",
    code: "REC-COR-016",
    name: "Mantar Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 30,
    calorie: 160,
    protein: 4.2,
    carb: 15.0,
    fat: 9.0,
    allergens: ["Gluten (Un)", "Laktoz (Krema/Süt/Tereyağı)"],
    instructions: "İnce kıyılmış kültür mantarları tereyağında suyunu çekene kadar sotelenir. Un ilavesiyle kavrulup sebze suyu ve krema eklenerek kıvam alır.",
    labor: 2.2, gas: 1.2, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_16_1", name: "Taze Kültür Mantarı", portionGrams: 65, unit: "g", unitCost: 80, portionCost: 5.2, wastagePercent: 8 },
      { id: "ing_cor_16_2", name: "Yemeklik Sıvı Krema", portionGrams: 30, unit: "ml", unitCost: 140, portionCost: 4.2, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_16_3", name: "Mutfak Tereyağı & Un", portionGrams: 16, unit: "g", unitCost: 180, portionCost: 2.88, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_16_4", name: "Tavuk / Sebze Suyu", portionGrams: 110, unit: "ml", unitCost: 30, portionCost: 3.3, wastagePercent: 0 },
      { id: "ing_cor_16_5", name: "Taze Dereotu & Karabiber", portionGrams: 4, unit: "g", unitCost: 65, portionCost: 0.26, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_17",
    code: "REC-COR-017",
    name: "Kremalı Tavuk Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 20,
    cookTime: 35,
    calorie: 185,
    protein: 12.0,
    carb: 14.0,
    fat: 9.5,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Haşlanmış tavuk göğsü ince tiftiklenir. Tereyağlı un meyanesi, taze tavuk suyu ve krema ile birleştirilip kısık ateşte pişirilir.",
    labor: 2.5, gas: 1.3, overhead: 0.6,
    ingredients: [
      { id: "ing_cor_17_1", name: "Didiklenmiş Tavuk Göğsü", portionGrams: 50, unit: "g", unitCost: 190, portionCost: 9.5, wastagePercent: 10 },
      { id: "ing_cor_17_2", name: "Tavuk Haşlama Suyu", portionGrams: 120, unit: "ml", unitCost: 25, portionCost: 3.0, wastagePercent: 0 },
      { id: "ing_cor_17_3", name: "Yemeklik Krema & Süt", portionGrams: 35, unit: "ml", unitCost: 130, portionCost: 4.55, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_17_4", name: "Tereyağı & Un", portionGrams: 15, unit: "g", unitCost: 180, portionCost: 2.7, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_17_5", name: "Havuç & Maydanoz", portionGrams: 15, unit: "g", unitCost: 30, portionCost: 0.45, wastagePercent: 5 }
    ]
  }),
  createRecipe({
    id: "rec_cor_18",
    code: "REC-COR-018",
    name: "Şehriye Çorbası (Tel Şehriye)",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 10,
    cookTime: 25,
    calorie: 135,
    protein: 4.0,
    carb: 22.0,
    fat: 3.8,
    allergens: ["Gluten (Şehriye)"],
    instructions: "Domates rendesi ve tereyağı kavrulur. Sıcak tavuk suyu ilave edilip kaynayınca tel şehriyeler eklenir ve yumuşayana kadar pişirilir.",
    labor: 1.8, gas: 1.0, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_18_1", name: "Tel Şehriye", portionGrams: 30, unit: "g", unitCost: 40, portionCost: 1.2, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_18_2", name: "Domates Salçası & Rendesi", portionGrams: 30, unit: "g", unitCost: 45, portionCost: 1.35, wastagePercent: 0 },
      { id: "ing_cor_18_3", name: "Tavuk Suyu", portionGrams: 120, unit: "ml", unitCost: 25, portionCost: 3.0, wastagePercent: 0 },
      { id: "ing_cor_18_4", name: "Sıvı Yağ & Tereyağı", portionGrams: 10, unit: "ml", unitCost: 180, portionCost: 1.8, wastagePercent: 0 },
      { id: "ing_cor_18_5", name: "İnce Kıyılmış Maydanoz", portionGrams: 5, unit: "g", unitCost: 50, portionCost: 0.25, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_19",
    code: "REC-COR-019",
    name: "Arpa Şehriye Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 10,
    cookTime: 25,
    calorie: 145,
    protein: 4.2,
    carb: 24.0,
    fat: 4.0,
    allergens: ["Gluten"],
    instructions: "Arpa şehriyeler hafif kavrulup domates sosu ve lezzetli kemik suyu ile buluşturulur, nane ile servis edilir.",
    labor: 1.8, gas: 1.0, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_19_1", name: "Arpa Şehriye", portionGrams: 35, unit: "g", unitCost: 40, portionCost: 1.4, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_19_2", name: "Domates & Biber Salçası", portionGrams: 18, unit: "g", unitCost: 75, portionCost: 1.35, wastagePercent: 0 },
      { id: "ing_cor_19_3", name: "Kemik Suyu", portionGrams: 120, unit: "ml", unitCost: 30, portionCost: 3.6, wastagePercent: 0 },
      { id: "ing_cor_19_4", name: "Tereyağı & Sıvı Yağ", portionGrams: 10, unit: "g", unitCost: 220, portionCost: 2.2, wastagePercent: 0 },
      { id: "ing_cor_19_5", name: "Kuru Nane & Limon", portionGrams: 6, unit: "g", unitCost: 60, portionCost: 0.36, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_20",
    code: "REC-COR-020",
    name: "Maş Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 20,
    cookTime: 45,
    calorie: 175,
    protein: 9.2,
    carb: 27.0,
    fat: 3.8,
    allergens: [],
    instructions: "Güneydoğu Anadolu klasiği maş fasulyesi haşlanır. Soğan, sarımsak, salça ve kimyonlu yağ gezdirilerek pişirilir.",
    labor: 2.2, gas: 1.4, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_20_1", name: "Maş Fasulyesi", portionGrams: 50, unit: "g", unitCost: 75, portionCost: 3.75, wastagePercent: 0 },
      { id: "ing_cor_20_2", name: "Kuru Soğan & Sarımsak", portionGrams: 30, unit: "g", unitCost: 22, portionCost: 0.66, wastagePercent: 10 },
      { id: "ing_cor_20_3", name: "Biber Salçası", portionGrams: 12, unit: "g", unitCost: 90, portionCost: 1.08, wastagePercent: 0 },
      { id: "ing_cor_20_4", name: "Zeytinyağı", portionGrams: 12, unit: "ml", unitCost: 280, portionCost: 3.36, wastagePercent: 0 },
      { id: "ing_cor_20_5", name: "Kimyon, Pul Biber, Tuz", portionGrams: 4, unit: "g", unitCost: 70, portionCost: 0.28, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_21",
    code: "REC-COR-021",
    name: "Toyga Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 20,
    cookTime: 40,
    calorie: 180,
    protein: 7.0,
    carb: 25.0,
    fat: 6.0,
    allergens: ["Laktoz", "Gluten", "Yumurta"],
    instructions: "Aşurelik buğday (yarma) ve haşlanmış nohut yoğurtlu-yumurtalı terbiye ile birleştirilir. Üzerine naneli kızgın tereyağı dökülür.",
    labor: 2.4, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_21_1", name: "Aşurelik Yarma Buğday", portionGrams: 30, unit: "g", unitCost: 45, portionCost: 1.35, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_21_2", name: "Haşlanmış Nohut", portionGrams: 25, unit: "g", unitCost: 65, portionCost: 1.63, wastagePercent: 0 },
      { id: "ing_cor_21_3", name: "Süzme Yoğurt & Yumurta", portionGrams: 60, unit: "g", unitCost: 75, portionCost: 4.5, wastagePercent: 0, allergen: "Laktoz, Yumurta" },
      { id: "ing_cor_21_4", name: "Mutfak Tereyağı & Nane", portionGrams: 12, unit: "g", unitCost: 260, portionCost: 3.12, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_22",
    code: "REC-COR-022",
    name: "Gendime Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 20,
    cookTime: 60,
    calorie: 210,
    protein: 9.5,
    carb: 28.0,
    fat: 7.2,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Erzurum ve Doğu Anadolu usulü gendime (yarma buğday), kemikli et suyu, kurutulmuş süzme yoğurt ve nane ile pişirilir.",
    labor: 2.5, gas: 1.6, overhead: 0.6,
    ingredients: [
      { id: "ing_cor_22_1", name: "Gendime (Dövme Buğday)", portionGrams: 40, unit: "g", unitCost: 45, portionCost: 1.8, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_22_2", name: "Kemikli Kuzu Suyu & Parça Et", portionGrams: 40, unit: "g", unitCost: 250, portionCost: 10.0, wastagePercent: 10 },
      { id: "ing_cor_22_3", name: "Yoğurt & Tereyağı", portionGrams: 40, unit: "g", unitCost: 150, portionCost: 6.0, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_22_4", name: "Kuru Nane & Dağ Kekiği", portionGrams: 5, unit: "g", unitCost: 80, portionCost: 0.4, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_23",
    code: "REC-COR-023",
    name: "Analı Kızlı Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 270,
    prepTime: 45,
    cookTime: 50,
    calorie: 290,
    protein: 16.5,
    carb: 30.0,
    fat: 12.0,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Kıymalı iç harçlı iri içli köfteler (analar) ile küçük bulgur topları (kızlar), nohut ve kuşbaşı etli salçalı nane suyunda pişirilir.",
    labor: 4.8, gas: 2.5, overhead: 1.0,
    ingredients: [
      { id: "ing_cor_23_1", name: "İçli Köfte (Analı)", portionGrams: 45, unit: "g", unitCost: 280, portionCost: 12.6, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_23_2", name: "Bulgur Topları (Kızlı)", portionGrams: 35, unit: "g", unitCost: 80, portionCost: 2.8, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_23_3", name: "Dana Kuşbaşı & Haşlanmış Nohut", portionGrams: 40, unit: "g", unitCost: 320, portionCost: 12.8, wastagePercent: 5 },
      { id: "ing_cor_23_4", name: "Salça, Tereyağı & Kuru Nane", portionGrams: 20, unit: "g", unitCost: 150, portionCost: 3.0, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_24",
    code: "REC-COR-024",
    name: "Umacı Çorbası (Yörük Çorbası)",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 30,
    calorie: 160,
    protein: 5.0,
    carb: 23.0,
    fat: 5.5,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Elde su ve un ile ovularak oluşturulan minik hamur taneleri (umac), tereyağlı naneli salçalı suda haşlanır.",
    labor: 2.2, gas: 1.2, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_24_1", name: "Umac Hamuru (Un & Su Ovması)", portionGrams: 45, unit: "g", unitCost: 40, portionCost: 1.8, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_24_2", name: "Tereyağı & Sıvı Yağ", portionGrams: 12, unit: "g", unitCost: 240, portionCost: 2.88, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_24_3", name: "Salça & Soğan Rendesi", portionGrams: 25, unit: "g", unitCost: 45, portionCost: 1.13, wastagePercent: 5 },
      { id: "ing_cor_24_4", name: "Kemik Suyu & Nane", portionGrams: 110, unit: "ml", unitCost: 30, portionCost: 3.3, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_25",
    code: "REC-COR-025",
    name: "Arabaşı Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 30,
    cookTime: 60,
    calorie: 210,
    protein: 15.0,
    carb: 14.0,
    fat: 10.0,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Didiklenmiş tavuk/hindi eti, kavrulmuş un meyanesi, bol acı pul biber ve tavuk suyu ile pişirilir. Özel soğuk arabaşı hamuru ile yutulur.",
    labor: 3.2, gas: 2.0, overhead: 0.8,
    ingredients: [
      { id: "ing_cor_25_1", name: "Didiklenmiş Köy Tavuğu / Hindi", portionGrams: 60, unit: "g", unitCost: 200, portionCost: 12.0, wastagePercent: 10 },
      { id: "ing_cor_25_2", name: "Tavuk Yağlı Haşlama Suyu", portionGrams: 130, unit: "ml", unitCost: 30, portionCost: 3.9, wastagePercent: 0 },
      { id: "ing_cor_25_3", name: "Kavrulmuş Un & Tereyağı", portionGrams: 20, unit: "g", unitCost: 160, portionCost: 3.2, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_25_4", name: "Acı Pul Biber & Salça", portionGrams: 15, unit: "g", unitCost: 80, portionCost: 1.2, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_26",
    code: "REC-COR-026",
    name: "Bademli Tavuk Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 20,
    cookTime: 35,
    calorie: 205,
    protein: 14.0,
    carb: 12.0,
    fat: 11.5,
    allergens: ["Kuruyemiş (Badem)", "Laktoz", "Gluten"],
    instructions: "Osmanlı saray mutfağı usulü soyulmuş tatlı bademler tereyağında kavrulur, tavuk eti, tavuk suyu ve sütlü terbiye ile birleştirilir.",
    labor: 2.8, gas: 1.4, overhead: 0.6,
    ingredients: [
      { id: "ing_cor_26_1", name: "Soyulmuş File Badem", portionGrams: 25, unit: "g", unitCost: 450, portionCost: 11.25, wastagePercent: 0, allergen: "Badem" },
      { id: "ing_cor_26_2", name: "Tavuk Göğüs Eti (Küp)", portionGrams: 45, unit: "g", unitCost: 190, portionCost: 8.55, wastagePercent: 5 },
      { id: "ing_cor_26_3", name: "Süt & Tereyağı", portionGrams: 50, unit: "ml", unitCost: 120, portionCost: 6.0, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_26_4", name: "Tavuk Suyu & Un", portionGrams: 90, unit: "ml", unitCost: 35, portionCost: 3.15, wastagePercent: 0, allergen: "Gluten" }
    ]
  }),
  createRecipe({
    id: "rec_cor_27",
    code: "REC-COR-027",
    name: "Sarımsaklı Çorba",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 30,
    calorie: 150,
    protein: 5.5,
    carb: 16.0,
    fat: 7.2,
    allergens: ["Laktoz", "Gluten"],
    instructions: "Bol diş sarımsak tereyağında kokusu yakılmadan kavrulur, kemik suyu ve yoğurtlu terbiye ile bağlanır. Doğal antibiyotik deposudur.",
    labor: 2.0, gas: 1.1, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_27_1", name: "Taşköprü Sarımsağı", portionGrams: 25, unit: "g", unitCost: 120, portionCost: 3.0, wastagePercent: 10 },
      { id: "ing_cor_27_2", name: "Mutfak Tereyağı", portionGrams: 15, unit: "g", unitCost: 320, portionCost: 4.8, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_27_3", name: "Yoğurtlu Terbiye & Un", portionGrams: 35, unit: "g", unitCost: 70, portionCost: 2.45, wastagePercent: 0, allergen: "Laktoz, Gluten" },
      { id: "ing_cor_27_4", name: "İlikli Et Suyu", portionGrams: 110, unit: "ml", unitCost: 35, portionCost: 3.85, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_28",
    code: "REC-COR-028",
    name: "Dutmaç Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 20,
    cookTime: 40,
    calorie: 195,
    protein: 8.5,
    carb: 27.0,
    fat: 6.0,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Eski Türk ve Selçuklu mutfağı mirası; ev eriştesi, mercimek, nohut ve yoğurtlu et suyuyla harmanlanıp üzerine reyhan ve tereyağı yakılır.",
    labor: 2.4, gas: 1.4, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_28_1", name: "Köy Eriştesi (Kesme)", portionGrams: 30, unit: "g", unitCost: 65, portionCost: 1.95, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_28_2", name: "Yeşil Mercimek & Nohut", portionGrams: 35, unit: "g", unitCost: 70, portionCost: 2.45, wastagePercent: 0 },
      { id: "ing_cor_28_3", name: "Süzme Yoğurt Terbiyesi", portionGrams: 50, unit: "g", unitCost: 70, portionCost: 3.5, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_28_4", name: "Tereyağı & Kuru Reyhan", portionGrams: 12, unit: "g", unitCost: 260, portionCost: 3.12, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_29",
    code: "REC-COR-029",
    name: "Kurut Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 20,
    cookTime: 35,
    calorie: 185,
    protein: 9.0,
    carb: 18.0,
    fat: 8.5,
    allergens: ["Laktoz", "Gluten"],
    instructions: "Geleneksel kurut (güneşte kurutulmuş ekşi yoğurt/keş) ılık suda ezilerek çözülür. Yarma ve tereyağlı soğanla kaynatılır.",
    labor: 2.3, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_29_1", name: "Geleneksel Kurut (Kuru Keş)", portionGrams: 40, unit: "g", unitCost: 180, portionCost: 7.2, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_29_2", name: "Dövme Yarma", portionGrams: 25, unit: "g", unitCost: 45, portionCost: 1.13, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_29_3", name: "Köy Tereyağı & Soğan", portionGrams: 25, unit: "g", unitCost: 160, portionCost: 4.0, wastagePercent: 5, allergen: "Laktoz" },
      { id: "ing_cor_29_4", name: "Nane & Pul Biber", portionGrams: 4, unit: "g", unitCost: 70, portionCost: 0.28, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_30",
    code: "REC-COR-030",
    name: "Oğmaç Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 30,
    calorie: 170,
    protein: 5.8,
    carb: 24.0,
    fat: 6.0,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Un, süt ve tereyağı ile yapılan ufak hamur tanecikleri tavuk suyunda haşlanır, naneli tereyağı ile tatlandırılır.",
    labor: 2.1, gas: 1.1, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_30_1", name: "Oğmaç Hamuru (Un, Süt)", portionGrams: 45, unit: "g", unitCost: 55, portionCost: 2.48, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_30_2", name: "Tavuk Suyu", portionGrams: 120, unit: "ml", unitCost: 25, portionCost: 3.0, wastagePercent: 0 },
      { id: "ing_cor_30_3", name: "Tereyağı & Salça", portionGrams: 15, unit: "g", unitCost: 200, portionCost: 3.0, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_30_4", name: "Nane & Karabiber", portionGrams: 4, unit: "g", unitCost: 65, portionCost: 0.26, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_31",
    code: "REC-COR-031",
    name: "Mahluta Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 40,
    calorie: 175,
    protein: 8.0,
    carb: 25.0,
    fat: 4.8,
    allergens: [],
    instructions: "Hatay mutfağına özgü kırmızı mercimek ve pirinç kimyonlu et suyunda pişirilir. Üzerine zeytinyağında kızdırılmış bol kişniş ve sarımsak dökülür.",
    labor: 2.2, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_31_1", name: "Kırmızı Mercimek & Pirinç", portionGrams: 45, unit: "g", unitCost: 50, portionCost: 2.25, wastagePercent: 0 },
      { id: "ing_cor_31_2", name: "Sızma Zeytinyağı", portionGrams: 15, unit: "ml", unitCost: 280, portionCost: 4.2, wastagePercent: 0 },
      { id: "ing_cor_31_3", name: "Sarımsak, Kişniş & Kimyon", portionGrams: 10, unit: "g", unitCost: 90, portionCost: 0.9, wastagePercent: 0 },
      { id: "ing_cor_31_4", name: "Doğal Et Suyu", portionGrams: 110, unit: "ml", unitCost: 35, portionCost: 3.85, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_32",
    code: "REC-COR-032",
    name: "Efike / Sütlü Çorba",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 30,
    calorie: 180,
    protein: 6.5,
    carb: 21.0,
    fat: 7.8,
    allergens: ["Laktoz", "Gluten"],
    instructions: "Yarma veya bulgurun süt ve et suyu ile ağır ağır kaynatılmasıyla elde edilen yumuşak içimli yöresel sütlü çorba.",
    labor: 2.1, gas: 1.2, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_32_1", name: "Dövme Yarma", portionGrams: 30, unit: "g", unitCost: 45, portionCost: 1.35, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_32_2", name: "Taze Çiftlik Sütü", portionGrams: 120, unit: "ml", unitCost: 35, portionCost: 4.2, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_32_3", name: "Mutfak Tereyağı", portionGrams: 12, unit: "g", unitCost: 320, portionCost: 3.84, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_32_4", name: "Kaya Tuzu & Beyaz Karabiber", portionGrams: 3, unit: "g", unitCost: 70, portionCost: 0.21, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_33",
    code: "REC-COR-033",
    name: "Yarma Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 45,
    calorie: 165,
    protein: 6.0,
    carb: 26.0,
    fat: 4.5,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Geleneksel aşurelik dövme yarma, nohut ve kemik suyu ile kıvam alana dek pişirilir; yoğurt ve nane sosuyla tamamlanır.",
    labor: 2.1, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_33_1", name: "Aşurelik Yarma Buğday", portionGrams: 45, unit: "g", unitCost: 45, portionCost: 2.03, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_33_2", name: "Kemik Suyu & Yoğurt Terbiyesi", portionGrams: 100, unit: "ml", unitCost: 40, portionCost: 4.0, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_33_3", name: "Tereyağı & Pul Biber", portionGrams: 10, unit: "g", unitCost: 300, portionCost: 3.0, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_34",
    code: "REC-COR-034",
    name: "Tutmaç Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 20,
    cookTime: 40,
    calorie: 195,
    protein: 8.0,
    carb: 28.0,
    fat: 5.8,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Yeşil mercimek ve el kesmesi erişte kemik suyunda pişirilir. Yoğurtlu terbiye ve tereyağında kavrulmuş soğan-nane sosu ile bağlanır.",
    labor: 2.3, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_34_1", name: "Yeşil Mercimek", portionGrams: 30, unit: "g", unitCost: 65, portionCost: 1.95, wastagePercent: 0 },
      { id: "ing_cor_34_2", name: "Ev Eriştesi", portionGrams: 25, unit: "g", unitCost: 70, portionCost: 1.75, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_34_3", name: "Süzme Yoğurt & Un", portionGrams: 40, unit: "g", unitCost: 75, portionCost: 3.0, wastagePercent: 0, allergen: "Laktoz, Gluten" },
      { id: "ing_cor_34_4", name: "Tereyağında Karamelize Soğan & Nane", portionGrams: 25, unit: "g", unitCost: 150, portionCost: 3.75, wastagePercent: 5, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_35",
    code: "REC-COR-035",
    name: "Brokoli Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 25,
    calorie: 130,
    protein: 4.8,
    carb: 12.0,
    fat: 7.0,
    allergens: ["Laktoz", "Gluten"],
    instructions: "Taze brokoli çiçekleri, patates ve pırasa sebze suyunda haşlanıp pürüzsüzleştirilir. Hafif krema ve tereyağı eklenir.",
    labor: 2.0, gas: 1.0, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_35_1", name: "Taze Brokoli", portionGrams: 80, unit: "g", unitCost: 55, portionCost: 4.4, wastagePercent: 15 },
      { id: "ing_cor_35_2", name: "Patates & Kuru Soğan", portionGrams: 35, unit: "g", unitCost: 20, portionCost: 0.7, wastagePercent: 10 },
      { id: "ing_cor_35_3", name: "Yemeklik Sıvı Krema", portionGrams: 25, unit: "ml", unitCost: 140, portionCost: 3.5, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_35_4", name: "Tereyağı & Tuz", portionGrams: 8, unit: "g", unitCost: 300, portionCost: 2.4, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_36",
    code: "REC-COR-036",
    name: "Kabak Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 25,
    calorie: 120,
    protein: 3.5,
    carb: 11.0,
    fat: 6.5,
    allergens: ["Laktoz"],
    instructions: "Sakız kabakları, taze dereotu ve patates tavuk suyunda haşlanır. Süt ve sızma zeytinyağı ile kadifemsi kıvama getirilir.",
    labor: 2.0, gas: 1.0, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_36_1", name: "Sakız Kabağı", portionGrams: 90, unit: "g", unitCost: 35, portionCost: 3.15, wastagePercent: 10 },
      { id: "ing_cor_36_2", name: "Taze Dereotu & Soğan", portionGrams: 25, unit: "g", unitCost: 40, portionCost: 1.0, wastagePercent: 5 },
      { id: "ing_cor_36_3", name: "Süt & Tavuk Suyu", portionGrams: 100, unit: "ml", unitCost: 35, portionCost: 3.5, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_36_4", name: "Zeytinyağı & Karabiber", portionGrams: 10, unit: "ml", unitCost: 280, portionCost: 2.8, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_37",
    code: "REC-COR-037",
    name: "Ispanak Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 25,
    calorie: 135,
    protein: 4.5,
    carb: 13.0,
    fat: 7.2,
    allergens: ["Laktoz", "Gluten"],
    instructions: "Taze ıspanak yaprakları soğanla sotelenir, un meyanesi ve kemik suyu ile pişirilip süt/krema ile tatlandırılır.",
    labor: 2.0, gas: 1.0, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_37_1", name: "Taze Ispanak Yaprağı", portionGrams: 85, unit: "g", unitCost: 45, portionCost: 3.83, wastagePercent: 18 },
      { id: "ing_cor_37_2", name: "Un & Tereyağı", portionGrams: 15, unit: "g", unitCost: 200, portionCost: 3.0, wastagePercent: 0, allergen: "Gluten, Laktoz" },
      { id: "ing_cor_37_3", name: "Kemik Suyu & Süt", portionGrams: 110, unit: "ml", unitCost: 35, portionCost: 3.85, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_37_4", name: "Muskat Rendesi & Tuz", portionGrams: 2, unit: "g", unitCost: 100, portionCost: 0.2, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_38",
    code: "REC-COR-038",
    name: "Karnabahar Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 30,
    calorie: 140,
    protein: 4.2,
    carb: 14.0,
    fat: 7.5,
    allergens: ["Laktoz"],
    instructions: "Fırınlanmış karnabahar ve pırasa tavuk suyunda pişirilir, zeytinyağı ve hafif süt ile blenderdan geçirilerek sunulur.",
    labor: 2.0, gas: 1.1, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_38_1", name: "Taze Karnabahar", portionGrams: 90, unit: "g", unitCost: 38, portionCost: 3.42, wastagePercent: 12 },
      { id: "ing_cor_38_2", name: "Patates & Soğan", portionGrams: 30, unit: "g", unitCost: 20, portionCost: 0.6, wastagePercent: 10 },
      { id: "ing_cor_38_3", name: "Süt & Tereyağı", portionGrams: 60, unit: "ml", unitCost: 80, portionCost: 4.8, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_38_4", name: "Zerdeçal & Karabiber", portionGrams: 3, unit: "g", unitCost: 80, portionCost: 0.24, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_39",
    code: "REC-COR-039",
    name: "Ekşili Çorba",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 20,
    cookTime: 40,
    calorie: 175,
    protein: 7.5,
    carb: 25.0,
    fat: 5.2,
    allergens: ["Gluten"],
    instructions: "Malatya ve Gaziantep usulü dövme buğday, nohut, semizotu veya pazı ekşi erik/sumak suyu ve nane ile kaynatılır.",
    labor: 2.2, gas: 1.3, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_39_1", name: "Yarma Buğday & Nohut", portionGrams: 40, unit: "g", unitCost: 55, portionCost: 2.2, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_39_2", name: "Semizotu / Pazı Yaprağı", portionGrams: 40, unit: "g", unitCost: 40, portionCost: 1.6, wastagePercent: 10 },
      { id: "ing_cor_39_3", name: "Doğal Sumak Ekşisi", portionGrams: 15, unit: "ml", unitCost: 80, portionCost: 1.2, wastagePercent: 0 },
      { id: "ing_cor_39_4", name: "Zeytinyağı & Nane", portionGrams: 12, unit: "ml", unitCost: 260, portionCost: 3.12, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_40",
    code: "REC-COR-040",
    name: "Gelin Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 15,
    cookTime: 35,
    calorie: 170,
    protein: 6.5,
    carb: 24.0,
    fat: 5.5,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Kırmızı mercimek, bulgur ve tel şehriyenin zengin et suyu ve tereyağlı salça meyanesi ile harmanlandığı lezzetli Anadolu çorbası.",
    labor: 2.1, gas: 1.2, overhead: 0.5,
    ingredients: [
      { id: "ing_cor_40_1", name: "Kırmızı Mercimek & Bulgur", portionGrams: 35, unit: "g", unitCost: 45, portionCost: 1.58, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_40_2", name: "Tel Şehriye", portionGrams: 15, unit: "g", unitCost: 40, portionCost: 0.6, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_40_3", name: "Et Suyu & Tereyağı", portionGrams: 100, unit: "ml", unitCost: 45, portionCost: 4.5, wastagePercent: 0, allergen: "Laktoz" },
      { id: "ing_cor_40_4", name: "Salça, Nane & Pul Biber", portionGrams: 12, unit: "g", unitCost: 80, portionCost: 0.96, wastagePercent: 0 }
    ]
  }),
  createRecipe({
    id: "rec_cor_41",
    code: "REC-COR-041",
    name: "Kavurma Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 260,
    prepTime: 20,
    cookTime: 40,
    calorie: 260,
    protein: 18.0,
    carb: 14.0,
    fat: 15.0,
    allergens: ["Gluten", "Laktoz"],
    instructions: "Kendi yağında kavrulmuş dana kavurma parçaları, sarımsaklı et suyu, arpa şehriye ve tereyağlı sos ile doyurucu şekilde hazırlanır.",
    labor: 3.2, gas: 2.0, overhead: 0.8,
    ingredients: [
      { id: "ing_cor_41_1", name: "Rize Tipi Dana Kavurma", portionGrams: 55, unit: "g", unitCost: 550, portionCost: 30.25, wastagePercent: 0 },
      { id: "ing_cor_41_2", name: "Arpa Şehriye", portionGrams: 20, unit: "g", unitCost: 40, portionCost: 0.8, wastagePercent: 0, allergen: "Gluten" },
      { id: "ing_cor_41_3", name: "Kemik Suyu", portionGrams: 120, unit: "ml", unitCost: 35, portionCost: 4.2, wastagePercent: 0 },
      { id: "ing_cor_41_4", name: "Sarımsak, Salça & Tereyağı", portionGrams: 15, unit: "g", unitCost: 180, portionCost: 2.7, wastagePercent: 0, allergen: "Laktoz" }
    ]
  }),
  createRecipe({
    id: "rec_cor_42",
    code: "REC-COR-042",
    name: "Pirinç Çorbası",
    category: "soup",
    categoryLabel: "Çorbalar",
    portionGrams: 250,
    prepTime: 10,
    cookTime: 30,
    calorie: 140,
    protein: 3.8,
    carb: 25.0,
    fat: 3.5,
    allergens: ["Laktoz"],
    instructions: "Baldo kırık pirinç leziz tavuk suyunda haşlanır; rendelenmiş domates, tereyağı ve kıyılmış maydanoz ile servis edilir.",
    labor: 1.8, gas: 1.0, overhead: 0.4,
    ingredients: [
      { id: "ing_cor_42_1", name: "Baldo Kırık Pirinç", portionGrams: 35, unit: "g", unitCost: 65, portionCost: 2.28, wastagePercent: 0 },
      { id: "ing_cor_42_2", name: "Tavuk Suyu", portionGrams: 130, unit: "ml", unitCost: 25, portionCost: 3.25, wastagePercent: 0 },
      { id: "ing_cor_42_3", name: "Domates Rendesi & Salça", portionGrams: 25, unit: "g", unitCost: 40, portionCost: 1.0, wastagePercent: 0 },
      { id: "ing_cor_42_4", name: "Tereyağı & Maydanoz", portionGrams: 10, unit: "g", unitCost: 220, portionCost: 2.2, wastagePercent: 0, allergen: "Laktoz" }
    ]
  })
];

const fileContent = `import { FoodRecipe } from "../../types";

export const soupRecipes: FoodRecipe[] = ${JSON.stringify(soups, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, '../src/data/recipes/soupRecipes.ts'), fileContent, 'utf8');
console.log(`Generated ${soups.length} soup recipes successfully.`);
