import { Contact, Invoice, Account, Transaction, Product, Quote, CompanySettings, Cheque, PromissoryNote, Branch, Warehouse, Employee, LeaveRequest, AdvanceRequest, LegalDeduction } from "./types";
import { generateMonthlyIntegratedData } from "./utils/generateMonthlyDemoData";

const generatedData = generateMonthlyIntegratedData();

export const initialCompanySettings: CompanySettings = {
  companyName: "Muavin Bilişim & Danışmanlık A.Ş.",
  companyTitle: "Muavin Bilişim Teknolojileri ve Danışmanlık Anonim Şirketi",
  taxpayerType: "Anonim Şirket",
  taxOffice: "Mecidiyeköy V.D.",
  taxNumber: "8470291038",
  tradeRegisterNo: "384910-5",
  mersisNo: "0847029103800001",
  address: "Büyükdere Cad. No:195 Maya Plaza Kat:8, Mecidiyeköy, Şişli / İstanbul",
  city: "İstanbul",
  district: "Şişli",
  neighborhood: "Mecidiyeköy",
  street: "Büyükdere Cad.",
  buildingNo: "195",
  doorNo: "Kat:8",
  postalCode: "34394",
  country: "Türkiye",
  addressDetails: {
    country: "Türkiye",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Mecidiyeköy",
    street: "Büyükdere Cad.",
    buildingNo: "195",
    doorNo: "Kat:8",
    postalCode: "34394",
    fullAddress: "Büyükdere Cad. No:195 Maya Plaza Kat:8, Mecidiyeköy, Şişli / İstanbul",
  },
  phone: "+90 (212) 444 0 999",
  email: "info@muavin.com.tr",
  website: "www.muavin.com.tr",
  logoUrl: "",
  defaultBankName: "Garanti BBVA - Levent Ticari Şubesi",
  defaultBankIban: "TR33 0006 2000 0000 0012 3456 78",
  currency: "₺",
  taxCredentials: {
    userCode: "3484702910",
    password: "••••••••",
    codeSecret: "GIB-84920",
  },
  sgkCredentials: {
    userCode: "28470291038",
    systemPassword: "••••••••",
    workplacePassword: "••••••••",
    workplaceRegistrationNo: "2.8470.01.01.1029384.034.01-12",
  },
};

export const initialBranches: Branch[] = [
  {
    id: "br_1",
    code: "SUB-001",
    name: "Merkez Genel Müdürlük",
    managerName: "Ahmet Yılmaz",
    phone: "+90 (212) 444 0 999",
    email: "merkez@muavin.com.tr",
    isMain: true,
    status: "active",
    address: {
      country: "Türkiye",
      city: "İstanbul",
      district: "Şişli",
      neighborhood: "Mecidiyeköy",
      street: "Büyükdere Cad.",
      buildingNo: "195",
      doorNo: "Kat:8",
      postalCode: "34394",
      fullAddress: "Büyükdere Cad. No:195 Maya Plaza Kat:8, Mecidiyeköy, Şişli / İstanbul",
    },
    createdAt: "2026-01-01",
  },
  {
    id: "br_2",
    code: "SUB-002",
    name: "Ankara Bölge Müdürlüğü",
    managerName: "Ayşe Kaya",
    phone: "+90 (312) 555 12 34",
    email: "ankara@muavin.com.tr",
    isMain: false,
    status: "active",
    address: {
      country: "Türkiye",
      city: "Ankara",
      district: "Çankaya",
      neighborhood: "Kavaklıdere",
      street: "Tunalı Hilmi Caddesi",
      buildingNo: "88",
      doorNo: "Daire:4",
      postalCode: "06680",
      fullAddress: "Tunalı Hilmi Cad. No:88 D:4 Kavaklıdere, Çankaya / Ankara",
    },
    createdAt: "2026-02-15",
  },
  {
    id: "br_3",
    code: "SUB-003",
    name: "İzmir Şubesi",
    managerName: "Mehmet Demir",
    phone: "+90 (232) 444 88 99",
    email: "izmir@muavin.com.tr",
    isMain: false,
    status: "active",
    address: {
      country: "Türkiye",
      city: "İzmir",
      district: "Konak",
      neighborhood: "Alsancak",
      street: "Atatürk Caddesi",
      buildingNo: "142",
      doorNo: "Kat:2",
      postalCode: "35220",
      fullAddress: "Atatürk Cad. No:142 K:2 Alsancak, Konak / İzmir",
    },
    createdAt: "2026-03-20",
  },
];

export const initialWarehouses: Warehouse[] = [
  {
    id: "wh_1",
    code: "DEP-001",
    name: "Gebze Lojistik & Ana Depo",
    type: "main",
    capacityM2: 2500,
    managerName: "Hasan Öztürk",
    phone: "+90 (262) 644 11 22",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    status: "active",
    address: {
      country: "Türkiye",
      city: "Kocaeli",
      district: "Gebze",
      neighborhood: "Güzeller",
      street: "Organize Sanayi Bölgesi 2. Cadde",
      buildingNo: "15",
      doorNo: "Blok A",
      postalCode: "41400",
      fullAddress: "OSB 2. Cad. No:15 Blok A, Güzeller, Gebze / Kocaeli",
    },
    createdAt: "2026-01-05",
  },
  {
    id: "wh_2",
    code: "DEP-002",
    name: "İkitelli Yedek Parça Deposu",
    type: "regional",
    capacityM2: 1200,
    managerName: "Ali Can",
    phone: "+90 (212) 549 00 11",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    status: "active",
    address: {
      country: "Türkiye",
      city: "İstanbul",
      district: "Başakşehir",
      neighborhood: "Ikitelli OSB",
      street: "Teknopark Sk.",
      buildingNo: "8",
      doorNo: "No:12",
      postalCode: "34490",
      fullAddress: "İkitelli OSB Teknopark Sk. No:8/12, Başakşehir / İstanbul",
    },
    createdAt: "2026-02-01",
  },
  {
    id: "wh_3",
    code: "DEP-003",
    name: "Ankara Lojistik Transit Depo",
    type: "transit",
    capacityM2: 800,
    managerName: "Selin Şahin",
    phone: "+90 (312) 395 77 88",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    status: "active",
    address: {
      country: "Türkiye",
      city: "Ankara",
      district: "Yenimahalle",
      neighborhood: "Ostim",
      street: "Macun Mahallesi 100. Yıl Bulvarı",
      buildingNo: "45",
      doorNo: "D:2",
      postalCode: "06374",
      fullAddress: "100. Yıl Bulvarı No:45/2 Ostim, Yenimahalle / Ankara",
    },
    createdAt: "2026-03-01",
  },
];

export const initialContacts: Contact[] = generatedData.contacts;

export const initialAccounts: Account[] = generatedData.accounts;
export const initialProducts: Product[] = generatedData.products;
export const initialInvoices: Invoice[] = generatedData.invoices;
export const initialTransactions: Transaction[] = generatedData.transactions;
export const initialQuotes: Quote[] = generatedData.quotes;
export const initialCheques: Cheque[] = generatedData.cheques;
export const initialPromissoryNotes: PromissoryNote[] = generatedData.promissoryNotes;

export const initialEmployees: Employee[] = [
  // ==========================================
  // MERKEZ GENEL MÜDÜRLÜK (br_1)
  // ==========================================
  {
    id: "emp_br1_mgr",
    tckn: "10293847562",
    fullName: "Ahmet Yılmaz",
    title: "Şube Müdürü / Genel Müdür",
    department: "Yönetim",
    startDate: "2022-01-10",
    birthDate: "1985-04-12",
    homeAddress: "Mecidiyeköy Mah. Büyükdere Cad. No:195 Şişli / İstanbul",
    phone: "+90 (212) 444 0 999",
    email: "ahmet.yilmaz@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 110000,
    foodAllowance: 5000,
    roadAllowance: 3500,
    hasBes: true,
    sgkOccupationCode: "1120.01",
    iban: "TR12 0006 2000 0000 0011 2233 00",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 20,
    usedAnnualLeave: 5,
    notes: "Merkez Genel Müdürlük Şube Sorumlusu",
    createdAt: "2022-01-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },
  {
    id: "emp_1",
    tckn: "19283746510",
    fullName: "Kaan Yılmaz",
    title: "Kıdemli Yazılım Mimarı",
    department: "Yazılım & IT",
    startDate: "2023-03-15",
    birthDate: "1991-05-12",
    homeAddress: "Atatürk Mah. Karanfil Sok. No:14 D:5 Kadıköy / İstanbul",
    phone: "+90 (532) 111 22 33",
    email: "kaan.yilmaz@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 85000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "2512.01",
    iban: "TR12 0006 2000 0000 0011 2233 44",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 4,
    notes: "Full-stack yazılım ekibi lideri",
    createdAt: "2023-03-15",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },
  {
    id: "emp_2",
    tckn: "28471920384",
    fullName: "Selin Aksoy",
    title: "Mali İşler & Muhasebe Uzmanı",
    department: "Muhasebe & Finans",
    startDate: "2024-01-10",
    birthDate: "1995-11-20",
    homeAddress: "Mecidiyeköy Mah. Gülbahar Cad. No:45 Kat:3 Şişli / İstanbul",
    phone: "+90 (533) 222 33 44",
    email: "selin.aksoy@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 62000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "2411.02",
    iban: "TR45 0006 2000 0000 0022 3344 55",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 2,
    notes: "Maliyet muhasebesi ve e-fatura operasyon sorumlusu",
    createdAt: "2024-01-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },
  {
    id: "emp_3",
    tckn: "39482019283",
    fullName: "Burak Kaya",
    title: "İnsan Kaynakları Uzmanı",
    department: "İnsan Kaynakları",
    startDate: "2024-06-01",
    birthDate: "1993-08-04",
    homeAddress: "Cevizli Mah. Bağdat Cad. No:110 Maltepe / İstanbul",
    phone: "+90 (535) 333 44 55",
    email: "burak.kaya@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 58000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "2423.01",
    iban: "TR78 0006 2000 0000 0033 4455 66",
    bankName: "Yapı Kredi",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 5,
    notes: "İşe alım ve özlük hakları sorumlusu",
    createdAt: "2024-06-01",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },

  // ==========================================
  // ANKARA BÖLGE MÜDÜRLÜĞÜ (br_2)
  // ==========================================
  {
    id: "emp_br2_mgr",
    tckn: "40192837465",
    fullName: "Ayşe Kaya",
    title: "Ankara Bölge Müdürü",
    department: "Yönetim",
    startDate: "2023-01-15",
    birthDate: "1987-09-22",
    homeAddress: "Kavaklıdere Tunalı Hilmi Cad. No:88 Çankaya / Ankara",
    phone: "+90 (312) 555 12 34",
    email: "ayse.kaya@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 95000,
    foodAllowance: 5000,
    roadAllowance: 3000,
    hasBes: true,
    sgkOccupationCode: "1120.02",
    iban: "TR11 0006 2000 0000 0044 1122 33",
    bankName: "VakıfBank",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 3,
    notes: "Ankara Bölge Müdürlüğü Sorumlusu",
    createdAt: "2023-01-15",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },
  {
    id: "emp_br2_staff1",
    tckn: "51203948576",
    fullName: "Merve Aydın",
    title: "Bölge Satış Uzmanı",
    department: "Satış & Pazarlama",
    startDate: "2024-03-01",
    birthDate: "1994-02-18",
    homeAddress: "Bahçelievler 7. Cadde No:42 Çankaya / Ankara",
    phone: "+90 (536) 555 66 77",
    email: "merve.aydin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 54000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "2431.01",
    iban: "TR22 0006 2000 0000 0055 2233 44",
    bankName: "Ziraat Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "Ankara ve İç Anadolu Bölgesi Kurumsal Müşteri Portföyü",
    createdAt: "2024-03-01",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },
  {
    id: "emp_br2_staff2",
    tckn: "62314059687",
    fullName: "Hakan Demir",
    title: "Müşteri İlişkileri Temsilcisi",
    department: "Müşteri Hizmetleri",
    startDate: "2024-08-10",
    birthDate: "1996-07-05",
    homeAddress: "Çayyolu Mah. 2432. Cadde No:15 Yenimahalle / Ankara",
    phone: "+90 (537) 666 77 88",
    email: "hakan.demir@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 48000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "3339.01",
    iban: "TR33 0006 2000 0000 0066 3344 55",
    bankName: "Halkbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Bölge müşteri destek ve çağrı kaydı yönetimi",
    createdAt: "2024-08-10",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },
  {
    id: "emp_br2_staff3",
    tckn: "73425160798",
    fullName: "Onur Arslan",
    title: "Bölge Operasyon Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2025-01-15",
    birthDate: "1992-12-11",
    homeAddress: "Eryaman Mah. 1. Etap No:88 Etimesgut / Ankara",
    phone: "+90 (538) 777 88 99",
    email: "onur.arslan@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 52000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "3331.02",
    iban: "TR44 0006 2000 0000 0077 4455 66",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Ankara bölge lojistik ve saha operasyon takibi",
    createdAt: "2025-01-15",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },

  // ==========================================
  // İZMİR ŞUBESİ (br_3)
  // ==========================================
  {
    id: "emp_br3_mgr",
    tckn: "84536271809",
    fullName: "Mehmet Demir",
    title: "İzmir Şube Müdürü",
    department: "Yönetim",
    startDate: "2023-05-01",
    birthDate: "1986-03-30",
    homeAddress: "Alsancak Atatürk Cad. No:142 Konak / İzmir",
    phone: "+90 (232) 444 88 99",
    email: "mehmet.demir@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 90000,
    foodAllowance: 5000,
    roadAllowance: 3000,
    hasBes: true,
    sgkOccupationCode: "1120.03",
    iban: "TR55 0006 2000 0000 0088 5566 77",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 2,
    notes: "İzmir Şube Sorumlusu",
    createdAt: "2023-05-01",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },
  {
    id: "emp_br3_staff1",
    tckn: "95647382910",
    fullName: "Cemal Yıldız",
    title: "Ege Bölge Saha Satış Temsilcisi",
    department: "Satış & Pazarlama",
    startDate: "2024-02-15",
    birthDate: "1993-10-14",
    homeAddress: "Mavişehir Yalı Mah. 6523. Sokak Karşıyaka / İzmir",
    phone: "+90 (539) 888 99 00",
    email: "cemal.yildiz@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 53000,
    foodAllowance: 4500,
    roadAllowance: 3000,
    hasBes: true,
    sgkOccupationCode: "2431.02",
    iban: "TR66 0006 2000 0000 0099 6677 88",
    bankName: "Akbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 3,
    notes: "Ege bölgesi bayii ve saha müşteri ilişkileri",
    createdAt: "2024-02-15",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },
  {
    id: "emp_br3_staff2",
    tckn: "10758493021",
    fullName: "Ezgi Çelik",
    title: "Şube Ön Muhasebe Elemanı",
    department: "Muhasebe & Finans",
    startDate: "2024-07-01",
    birthDate: "1997-06-25",
    homeAddress: "Göztepe Mah. Mithatpaşa Cad. No:210 Konak / İzmir",
    phone: "+90 (540) 999 00 11",
    email: "ezgi.celik@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 46000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "4311.01",
    iban: "TR77 0006 2000 0000 0011 7788 99",
    bankName: "Yapı Kredi",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "İzmir şubesi kasa, fatura ve cari hesap mutabakatları",
    createdAt: "2024-07-01",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },
  {
    id: "emp_br3_staff3",
    tckn: "21869504132",
    fullName: "Tolga Şahin",
    title: "Lojistik & Müşteri Hizmetleri",
    department: "Müşteri Hizmetleri",
    startDate: "2025-02-01",
    birthDate: "1995-01-08",
    homeAddress: "Bornova Küçükpark Mah. 162. Sokak No:12 Bornova / İzmir",
    phone: "+90 (541) 000 11 22",
    email: "tolga.sahin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 47000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "3339.02",
    iban: "TR88 0006 2000 0000 0022 8899 00",
    bankName: "DenizBank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "İzmir şubesi sevkiyat bilgilendirme ve müşteri ilişkileri",
    createdAt: "2025-02-01",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },

  // ==========================================
  // GEBZE LOJİSTİK & ANA DEPO (wh_1)
  // ==========================================
  {
    id: "emp_wh1_mgr",
    tckn: "32970615243",
    fullName: "Hasan Öztürk",
    title: "Ana Depo Müdürü / Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2023-02-10",
    birthDate: "1984-07-19",
    homeAddress: "Güzeller Mah. OSB 2. Cadde No:15 Gebze / Kocaeli",
    phone: "+90 (262) 644 11 22",
    email: "hasan.ozturk@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 68000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "1324.01",
    iban: "TR99 0006 2000 0000 0033 9900 11",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 4,
    notes: "Gebze Lojistik Ana Depo Sorumlusu",
    createdAt: "2023-02-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },
  {
    id: "emp_wh1_staff1",
    tckn: "43081726354",
    fullName: "Ahmet Tunç",
    title: "Depo Mal Kabul Operatörü",
    department: "Operasyon & Lojistik",
    startDate: "2024-04-01",
    birthDate: "1996-09-12",
    homeAddress: "İnönü Mah. Gençlik Cad. No:34 Gebze / Kocaeli",
    phone: "+90 (542) 111 22 33",
    email: "ahmet.tunc@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 42000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "4321.01",
    iban: "TR10 0006 2000 0000 0044 0011 22",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 2,
    notes: "Tedarikçi teslimatı mal kabul ve barkodlama",
    createdAt: "2024-04-01",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },
  {
    id: "emp_wh1_staff2",
    tckn: "54192837465",
    fullName: "Mustafa Erdem",
    title: "Forklift & İstif Operatörü",
    department: "Operasyon & Lojistik",
    startDate: "2024-09-15",
    birthDate: "1992-11-03",
    homeAddress: "Mustafapaşa Mah. Bağdat Cad. No:78 Gebze / Kocaeli",
    phone: "+90 (543) 222 33 44",
    email: "mustafa.erdem@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 44000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "8334.01",
    iban: "TR21 0006 2000 0000 0055 1122 33",
    bankName: "Ziraat Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "Sertifikalı ağır istif ve raflama operatörü",
    createdAt: "2024-09-15",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },
  {
    id: "emp_wh1_staff3",
    tckn: "65203948576",
    fullName: "Emre Kılıç",
    title: "Stok & Envanter Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2025-01-10",
    birthDate: "1994-05-28",
    homeAddress: "Arapçeşme Mah. 1022. Sokak No:5 Darıca / Kocaeli",
    phone: "+90 (544) 333 44 55",
    email: "emre.kilic@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 46000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "4321.02",
    iban: "TR32 0006 2000 0000 0066 2233 44",
    bankName: "Yapı Kredi",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Periyodik depo sayımı ve kayıp/kaçak kontrolü",
    createdAt: "2025-01-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },

  // ==========================================
  // İKİTELLİ YEDEK PARÇA DEPOSU (wh_2)
  // ==========================================
  {
    id: "emp_wh2_mgr",
    tckn: "76314059687",
    fullName: "Ali Can",
    title: "Yedek Parça Depo Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2023-04-12",
    birthDate: "1988-12-04",
    homeAddress: "İkitelli OSB Teknopark Sk. No:8/12 Başakşehir / İstanbul",
    phone: "+90 (212) 549 00 11",
    email: "ali.can@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 65000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "1324.02",
    iban: "TR43 0006 2000 0000 0077 3344 55",
    bankName: "Akbank",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 3,
    notes: "İkitelli Yedek Parça Depo Sorumlusu",
    createdAt: "2023-04-12",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },
  {
    id: "emp_wh2_staff1",
    tckn: "87425160798",
    fullName: "Tarık Şahin",
    title: "Yedek Parça Sayım Elemanı",
    department: "Operasyon & Lojistik",
    startDate: "2024-05-15",
    birthDate: "1997-03-17",
    homeAddress: "Halkalı Merkez Mah. Dereboyu Cad. No:44 Küçükçekmece / İstanbul",
    phone: "+90 (545) 444 55 66",
    email: "tarik.sahin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 41000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "4321.03",
    iban: "TR54 0006 2000 0000 0088 4455 66",
    bankName: "QNB Finansbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 2,
    notes: "Otomotiv ve makine yedek parça kodlama takibi",
    createdAt: "2024-05-15",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },
  {
    id: "emp_wh2_staff2",
    tckn: "98536271809",
    fullName: "Serkan Yalçın",
    title: "Paketleme & Etiketleme Elemanı",
    department: "Operasyon & Lojistik",
    startDate: "2024-10-01",
    birthDate: "1999-08-22",
    homeAddress: "Mehmet Akif Mah. Aşık Veysel Cad. No:19 Küçükçekmece / İstanbul",
    phone: "+90 (546) 555 66 77",
    email: "serkan.yalcin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 40000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "9329.01",
    iban: "TR65 0006 2000 0000 0099 5566 77",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Kargo ve kurye paketleme ve etiket basım alanı",
    createdAt: "2024-10-01",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },
  {
    id: "emp_wh2_staff3",
    tckn: "10947382910",
    fullName: "Murat Yıldırım",
    title: "Sipariş Hazırlama Operatörü",
    department: "Operasyon & Lojistik",
    startDate: "2025-02-10",
    birthDate: "1995-04-14",
    homeAddress: "Ziya Gökalp Mah. Hürriyet Bulvarı No:90 Başakşehir / İstanbul",
    phone: "+90 (547) 666 77 88",
    email: "murat.yildirim@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 43000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "4321.04",
    iban: "TR76 0006 2000 0000 0010 6677 88",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "E-ticaret ve bayii sipariş toplama / toplama listesi operasyonu",
    createdAt: "2025-02-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },

  // ==========================================
  // ANKARA LOJİSTİK TRANSİT DEPO (wh_3)
  // ==========================================
  {
    id: "emp_wh3_mgr",
    tckn: "21058493021",
    fullName: "Selin Şahin",
    title: "Transit Depo Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2023-06-01",
    birthDate: "1989-10-08",
    homeAddress: "Ostim 100. Yıl Bulvarı No:45/2 Yenimahalle / Ankara",
    phone: "+90 (312) 395 77 88",
    email: "selin.sahin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 63000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "1324.03",
    iban: "TR87 0006 2000 0000 0021 7788 99",
    bankName: "VakıfBank",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 2,
    notes: "Ankara Lojistik Transit Depo Sorumlusu",
    createdAt: "2023-06-01",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
  {
    id: "emp_wh3_staff1",
    tckn: "32169504132",
    fullName: "Deniz Güneş",
    title: "Transit Sevkiyat Koordinatörü",
    department: "Operasyon & Lojistik",
    startDate: "2024-06-15",
    birthDate: "1994-01-30",
    homeAddress: "Macun Mah. Bağdat Cad. No:112 Yenimahalle / Ankara",
    phone: "+90 (548) 777 88 99",
    email: "deniz.gunes@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 45000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "3331.03",
    iban: "TR98 0006 2000 0000 0032 8899 00",
    bankName: "Ziraat Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "Şehirlerarası tır ve araç sevk planlaması",
    createdAt: "2024-06-15",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
  {
    id: "emp_wh3_staff2",
    tckn: "43270615243",
    fullName: "Onur Şimşek",
    title: "Saha & Yükleme Elemanı",
    department: "Operasyon & Lojistik",
    startDate: "2024-11-10",
    birthDate: "1998-07-21",
    homeAddress: "Şentepe Mah. Seval Cad. No:83 Yenimahalle / Ankara",
    phone: "+90 (549) 888 99 00",
    email: "onur.simsek@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 41000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "9333.01",
    iban: "TR09 0006 2000 0000 0043 9900 11",
    bankName: "Halkbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Transit araç yükleme ve boşaltma operasyonu",
    createdAt: "2024-11-10",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
  {
    id: "emp_wh3_staff3",
    tckn: "54381726354",
    fullName: "Elif Bozkurt",
    title: "Depo Giriş/Çıkış Kayıt Görevlisi",
    department: "Operasyon & Lojistik",
    startDate: "2025-01-20",
    birthDate: "1996-12-02",
    homeAddress: "Batıkent Kentkoop Mah. 1868. Sokak No:24 Yenimahalle / Ankara",
    phone: "+90 (550) 999 00 11",
    email: "elif.bozkurt@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 42000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "4321.05",
    iban: "TR10 0006 2000 0000 0054 0011 22",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "İrsaliye ve transit irsaliye giriş-çıkış evrak takibi",
    createdAt: "2025-01-20",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "lv_1",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    type: "Yıllık İzin",
    startDate: "2026-08-10",
    endDate: "2026-08-14",
    daysCount: 5,
    status: "approved",
    reason: "Yaz dönemi yıllık izin kullanımı",
    createdAt: "2026-07-20",
  },
  {
    id: "lv_2",
    employeeId: "emp_2",
    employeeName: "Selin Aksoy",
    type: "Sıhhi İzin",
    startDate: "2026-07-15",
    endDate: "2026-07-18",
    daysCount: 4,
    status: "approved",
    reason: "Doktor raporlu sıhhi izin (2 günü aşan 2 gün maaştan kesilir)",
    createdAt: "2026-07-14",
  },
  {
    id: "lv_3",
    employeeId: "emp_3",
    employeeName: "Emre Öztürk",
    type: "Ücretsiz İzin",
    startDate: "2026-07-01",
    endDate: "2026-07-03",
    daysCount: 3,
    status: "approved",
    reason: "Kişisel işler nedeniyle ücretsiz izin (Maaştan kesilir)",
    createdAt: "2026-06-28",
  },
  {
    id: "lv_4",
    employeeId: "emp_4",
    employeeName: "Zeynep Kaya",
    type: "Mazeretsiz İzin",
    startDate: "2026-07-10",
    endDate: "2026-07-10",
    daysCount: 1,
    status: "approved",
    reason: "Mazeretsiz işe gelmeme / Devamsızlık (Maaştan kesilir)",
    createdAt: "2026-07-10",
  },
  {
    id: "lv_5",
    employeeId: "emp_5",
    employeeName: "Burak Demir",
    type: "Ücretli İzin",
    startDate: "2026-07-28",
    endDate: "2026-07-28",
    daysCount: 1,
    status: "pending",
    reason: "İdari resmi randevu ücretli izni",
    createdAt: "2026-07-24",
  },
];

export const initialAdvanceRequests: AdvanceRequest[] = [
  {
    id: "adv_1",
    employeeId: "emp_3",
    employeeName: "Emre Öztürk",
    type: "Masraf",
    amount: 3450,
    requestDate: "2026-07-22",
    description: "Ankara Müşteri Ziyareti - Hızlı Tren ve Otel Konaklama",
    status: "paid",
    createdAt: "2026-07-22",
  },
  {
    id: "adv_2",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    type: "Avans",
    amount: 15000,
    requestDate: "2026-07-24",
    description: "Maaş öncesi kısıtlı avans talebi",
    status: "pending",
    createdAt: "2026-07-24",
  },
];

export const initialLegalDeductions: LegalDeduction[] = [
  {
    id: "leg_1",
    employeeId: "emp_1", // Kaan Yılmaz
    employeeName: "Kaan Yılmaz",
    type: "İcra Kesintisi",
    fileNumber: "İstanbul 8. İcra Dairesi 2025/11204 Esas",
    creditorName: "Garanti BBVA A.Ş. Vekili",
    iban: "TR12 0006 2000 0000 0011 2233 44",
    totalDebtAmount: 60000,
    paidAmount: 25000,
    monthlyAmount: 8750,
    calculationType: "quarter_salary",
    priorityOrder: 1,
    status: "active",
    notes: "1. Sıradaki aktif icra dosyası. Maaşının 1/4'ü oranında kesinti yapılıyor.",
    createdAt: "2025-11-10",
  },
  {
    id: "leg_2",
    employeeId: "emp_1", // Kaan Yılmaz - 2. İcra dosyası (Sırada Bekliyor!)
    employeeName: "Kaan Yılmaz",
    type: "İcra Kesintisi",
    fileNumber: "Ankara 3. İcra Dairesi 2026/4582 Esas",
    creditorName: "Yapı Kredi Bankası A.Ş.",
    iban: "TR45 0006 7000 0000 0055 6677 88",
    totalDebtAmount: 40000,
    paidAmount: 0,
    monthlyAmount: 7500,
    calculationType: "fixed",
    priorityOrder: 2,
    status: "queued",
    notes: "2. Sıradaki icra dosyası. 1. Sıradaki borç bittiğinde otomatik aktifleşir.",
    createdAt: "2026-02-15",
  },
  {
    id: "leg_3",
    employeeId: "emp_2", // Selin Aksoy - Nafaka Kesintisi
    employeeName: "Selin Aksoy",
    type: "Nafaka Kesintisi",
    fileNumber: "Kadıköy 2. Aile Mahkemesi 2024/912 Esas",
    creditorName: "Ahmet Aksoy (Çocuk Nafakası)",
    iban: "TR98 0001 5000 0000 0099 8877 66",
    totalDebtAmount: 0, // Sürekli / Aylık nafaka
    paidAmount: 36000,
    monthlyAmount: 6000,
    calculationType: "fixed",
    priorityOrder: 1,
    status: "active",
    notes: "Aylık ilamlı çocuk nafaka kesintisi.",
    createdAt: "2024-05-01",
  },
];

