import { Contact, Invoice, Account, Transaction, Product, Quote, Order, Waybill, CompanySettings, Cheque, PromissoryNote, Branch, Warehouse, Employee, LeaveRequest, AdvanceRequest, LegalDeduction, CostProject, AssetCustody, BillOfMaterials, Workstation, Routing, WorkOrder, SubcontractOrder } from "./types";
import { generateMonthlyIntegratedData } from "./utils/generateMonthlyDemoData";

const generatedData = generateMonthlyIntegratedData();

export const initialCompanySettings: CompanySettings = {
  companyName: "Muavin Bilişim & Danışmanlık A.Ş.",
  companyTitle: "Muavin Bilişim Teknolojileri ve Danışmanlık Anonim Şirketi",
  taxpayerType: "Anonim Şirket",
  taxOffice: "Mecidiyeköy V.D.",
  taxNumber: "8470291038",
  tradeRegisterNo: "384910-5",
  mersisNo: "0847029103800001",
  address: "Büyükdere Cad. No:195 Maya Plaza Kat:8, Mecidiyeköy, Şişli / İstanbul",
  city: "İstanbul",
  district: "Şişli",
  neighborhood: "Mecidiyeköy",
  street: "Büyükdere Cad.",
  buildingNo: "195",
  doorNo: "Kat:8",
  postalCode: "34394",
  country: "Türkiye",
  addressDetails: {
    country: "Türkiye",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Mecidiyeköy",
    street: "Büyükdere Cad.",
    buildingNo: "195",
    doorNo: "Kat:8",
    postalCode: "34394",
    fullAddress: "Büyükdere Cad. No:195 Maya Plaza Kat:8, Mecidiyeköy, Şişli / İstanbul",
  },
  phone: "+90 (212) 444 0 999",
  email: "info@muavin.com.tr",
  website: "www.muavin.com.tr",
  logoUrl: "",
  defaultBankName: "Garanti BBVA - Levent Ticari Şubesi",
  defaultBankIban: "TR33 0006 2000 0000 0012 3456 78",
  currency: "₺",
  taxCredentials: {
    userCode: "3484702910",
    password: "••••••••",
    codeSecret: "GIB-84920",
  },
  sgkCredentials: {
    userCode: "28470291038",
    workplaceCode: "000",
    systemPassword: "••••••••",
    workplacePassword: "••••••••",
    workplaceRegistrationNo: "28470010110293840340112",
    workplaces: [
      {
        id: "sgk_wp_1",
        name: "Merkez (Genel Müdürlük)",
        type: "main",
        referenceId: "br_1",
        workplaceRegistrationNo: "28470010110293840340112",
        userCode: "28470291038",
        workplaceCode: "000",
        systemPassword: "••••••••",
        workplacePassword: "••••••••",
      },
      {
        id: "sgk_wp_2",
        name: "Ankara Bölge Müdürlüğü (Şube)",
        type: "branch",
        referenceId: "br_2",
        workplaceRegistrationNo: "20600010110283920060215",
        userCode: "20600028392",
        workplaceCode: "001",
        systemPassword: "••••••••",
        workplacePassword: "••••••••",
      },
      {
        id: "sgk_wp_3",
        name: "Gebze Lojistik & Ana Depo",
        type: "warehouse",
        referenceId: "wh_1",
        workplaceRegistrationNo: "24100010110938470410105",
        userCode: "24100093847",
        workplaceCode: "002",
        systemPassword: "••••••••",
        workplacePassword: "••••••••",
      },
    ],
  },
  eDevletCredentials: {
    managerName: "Ahmet Yılmaz",
    tcKimlikNo: "18492048592",
    eDevletPassword: "••••••••",
    mobileSignaturePhone: "+90 (532) 555 12 34",
  },
  eTebligatlar: [
    {
      id: "eteb_1",
      authority: "GIB",
      senderUnit: "Mecidiyeköy Vergi Dairesi Müdürlüğü",
      documentTitle: "İzahata Davet Yazısı (VUK 370. Madde Uyarınca)",
      documentType: "İzahata Davet",
      barcodeNumber: "GIB-2026-ETEB-8492019",
      envelopeId: "e-ZRF-2026-948204",
      sentDate: "2026-08-16",
      deliveryDate: "2026-08-21",
      legalDeadlineDate: "2026-09-05",
      status: "unread",
      contentSummary: "2026/04 dönemine ait Form Ba/Bs bildirimlerinde tedarikçi faturaları ile beyan edilen matrahlar arasındaki çapraz kontrol uyuşmazlığına ilişkin 30 gün içinde izahat verilmesi talep edilmektedir.",
      notes: "Mali müşavir ile görüşülüp fatura listeleri karşılaştırılacak.",
      amount: 0,
      receiptNumber: "MZB-GIB-2026-00492",
    },
    {
      id: "eteb_2",
      authority: "SGK",
      senderUnit: "İstanbul Sosyal Güvenlik İl Müdürlüğü (Şişli SGM)",
      documentTitle: "5510 Sayılı Kanun Kapsamında Prim Teşvik Uygunluk & Mahsup Bildirimi",
      documentType: "Teşvik Bildirimi",
      barcodeNumber: "SGK-2026-TEB-3829104",
      envelopeId: "e-ZRF-2026-118492",
      sentDate: "2026-08-14",
      deliveryDate: "2026-08-19",
      legalDeadlineDate: "2026-09-18",
      status: "read",
      contentSummary: "2026/06 döneminde uygulanan %5 Hazine desteği ve ilave istihdam prim teşviklerinin denetimi tamamlanmış olup ilgili tutarlar prim hesabına mahsup edilmiştir.",
      workplaceId: "sgk_wp_1",
      workplaceName: "Merkez (Genel Müdürlük)",
      notes: "Bordro ve muhasebe kayıtlarına işlendi.",
      amount: 14850,
      receiptNumber: "MZB-SGK-2026-00812",
    },
    {
      id: "eteb_3",
      authority: "GIB",
      senderUnit: "Gelir İdaresi Başkanlığı / Büyük Mükellefler V.D.",
      documentTitle: "2026/05 Dönemi KDV İadesi Mahsup ve Mahsup Talebi Uygunluk Belgesi",
      documentType: "KDV İade / Mahsup",
      barcodeNumber: "GIB-2026-ETEB-1948203",
      envelopeId: "e-ZRF-2026-559102",
      sentDate: "2026-08-10",
      deliveryDate: "2026-08-15",
      legalDeadlineDate: "2026-09-14",
      status: "paid",
      contentSummary: "İhracat istisnası kaynaklı KDV iade talebiniz vergi dairesince onaylanmış ve sonraki dönem SGK prim borçlarına mahsup işlemi gerçekleştirilmiştir.",
      notes: "Mahsup makbuzu alındı.",
      amount: 42350,
      receiptNumber: "MZB-GIB-2026-00219",
    },
    {
      id: "eteb_4",
      authority: "SGK",
      senderUnit: "Ankara Sosyal Güvenlik İl Müdürlüğü (Çankaya SGM)",
      documentTitle: "İdari Para Cezası ve Eksik Gün Bildirim Yazısı",
      documentType: "İdari Para Cezası",
      barcodeNumber: "SGK-2026-TEB-9104823",
      envelopeId: "e-ZRF-2026-448201",
      sentDate: "2026-08-08",
      deliveryDate: "2026-08-13",
      legalDeadlineDate: "2026-08-28",
      status: "in_process",
      contentSummary: "Ankara Bölge Şubesi nezdinde 2026/04 döneminde bildirilen eksik gün kodunun (07 Kod Puantaj Kaydı) belgelendirilmesi talebi.",
      workplaceId: "sgk_wp_2",
      workplaceName: "Ankara Bölge & Satış Şubesi",
      notes: "Puantaj kayıtları ve imzalı bordrolar sisteme yüklenecek.",
      amount: 4850,
      receiptNumber: "MZB-SGK-2026-00384",
    },
  ],
};

export const initialBranches: Branch[] = [
  {
    id: "br_1",
    code: "SUB-001",
    name: "Merkez Genel Müdürlük",
    managerName: "Ahmet Yılmaz",
    phone: "+90 (212) 444 0 999",
    email: "merkez@muavin.com.tr",
    isMain: true,
    status: "active",
    address: {
      country: "Türkiye",
      city: "İstanbul",
      district: "Şişli",
      neighborhood: "Mecidiyeköy",
      street: "Büyükdere Cad.",
      buildingNo: "195",
      doorNo: "Kat:8",
      postalCode: "34394",
      fullAddress: "Büyükdere Cad. No:195 Maya Plaza Kat:8, Mecidiyeköy, Şişli / İstanbul",
    },
    createdAt: "2026-01-01",
  },
  {
    id: "br_2",
    code: "SUB-002",
    name: "Ankara Bölge Müdürlüğü",
    managerName: "Ayşe Kaya",
    phone: "+90 (312) 555 12 34",
    email: "ankara@muavin.com.tr",
    isMain: false,
    status: "active",
    address: {
      country: "Türkiye",
      city: "Ankara",
      district: "Çankaya",
      neighborhood: "Kavaklıdere",
      street: "Tunalı Hilmi Caddesi",
      buildingNo: "88",
      doorNo: "Daire:4",
      postalCode: "06680",
      fullAddress: "Tunalı Hilmi Cad. No:88 D:4 Kavaklıdere, Çankaya / Ankara",
    },
    createdAt: "2026-02-15",
  },
  {
    id: "br_3",
    code: "SUB-003",
    name: "İzmir Şubesi",
    managerName: "Mehmet Demir",
    phone: "+90 (232) 444 88 99",
    email: "izmir@muavin.com.tr",
    isMain: false,
    status: "active",
    address: {
      country: "Türkiye",
      city: "İzmir",
      district: "Konak",
      neighborhood: "Alsancak",
      street: "Atatürk Caddesi",
      buildingNo: "142",
      doorNo: "Kat:2",
      postalCode: "35220",
      fullAddress: "Atatürk Cad. No:142 K:2 Alsancak, Konak / İzmir",
    },
    createdAt: "2026-03-20",
  },
];

export const initialWarehouses: Warehouse[] = [
  {
    id: "wh_1",
    code: "DEP-001",
    name: "Gebze Lojistik & Ana Depo",
    type: "main",
    capacityM2: 2500,
    managerName: "Hasan Öztürk",
    phone: "+90 (262) 644 11 22",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    status: "active",
    address: {
      country: "Türkiye",
      city: "Kocaeli",
      district: "Gebze",
      neighborhood: "Güzeller",
      street: "Organize Sanayi Bölgesi 2. Cadde",
      buildingNo: "15",
      doorNo: "Blok A",
      postalCode: "41400",
      fullAddress: "OSB 2. Cad. No:15 Blok A, Güzeller, Gebze / Kocaeli",
    },
    createdAt: "2026-01-05",
  },
  {
    id: "wh_2",
    code: "DEP-002",
    name: "İkitelli Yedek Parça Deposu",
    type: "regional",
    capacityM2: 1200,
    managerName: "Ali Can",
    phone: "+90 (212) 549 00 11",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    status: "active",
    address: {
      country: "Türkiye",
      city: "İstanbul",
      district: "Başakşehir",
      neighborhood: "Ikitelli OSB",
      street: "Teknopark Sk.",
      buildingNo: "8",
      doorNo: "No:12",
      postalCode: "34490",
      fullAddress: "İkitelli OSB Teknopark Sk. No:8/12, Başakşehir / İstanbul",
    },
    createdAt: "2026-02-01",
  },
  {
    id: "wh_3",
    code: "DEP-003",
    name: "Ankara Lojistik Transit Depo",
    type: "transit",
    capacityM2: 800,
    managerName: "Selin Şahin",
    phone: "+90 (312) 395 77 88",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    status: "active",
    address: {
      country: "Türkiye",
      city: "Ankara",
      district: "Yenimahalle",
      neighborhood: "Ostim",
      street: "Macun Mahallesi 100. Yıl Bulvarı",
      buildingNo: "45",
      doorNo: "D:2",
      postalCode: "06374",
      fullAddress: "100. Yıl Bulvarı No:45/2 Ostim, Yenimahalle / Ankara",
    },
    createdAt: "2026-03-01",
  },
];

export const initialContacts: Contact[] = generatedData.contacts;

export const initialAccounts: Account[] = generatedData.accounts;
export const initialProducts: Product[] = generatedData.products;
export const initialInvoices: Invoice[] = generatedData.invoices;
export const initialTransactions: Transaction[] = generatedData.transactions;
export const initialQuotes: Quote[] = generatedData.quotes;
export const initialCheques: Cheque[] = generatedData.cheques;
export const initialPromissoryNotes: PromissoryNote[] = generatedData.promissoryNotes;

export const initialWaybills: Waybill[] = [
  {
    id: "way_1",
    waybillNumber: "IRS-2026-00101",
    type: "dispatch",
    contactId: "cnt_1",
    contactName: "Borusan Lojistik A.Ş.",
    contactPhone: "+90 (212) 393 50 00",
    taxNumber: "1800034920",
    waybillDate: "2026-07-20",
    dispatchDate: "2026-07-20 10:30",
    vehiclePlate: "34 BRS 102",
    driverName: "Murat Demir (TC: 10293847562)",
    deliveryAddress: "Güzeller OSB 2. Cad. No:15 Gebze / Kocaeli",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
    items: [
      {
        id: "w_item_1",
        productId: "prod_1",
        productCode: "STK-1001",
        description: "Endüstriyel Konvektör Fırın 10 Tepsi",
        quantity: 2,
        unit: "Adet",
        unitPrice: 42500,
        vatRate: 20,
        discountRate: 0,
        totalWithoutVat: 85000,
        vatAmount: 17000,
        totalWithVat: 102000,
      }
    ],
    subtotal: 85000,
    totalVat: 17000,
    grandTotal: 102000,
    currency: "₺",
    status: "shipped",
    notes: "Şoför teslimat imzası alındığında faturalandırılacaktır.",
    createdAt: "2026-07-20",
  },
  {
    id: "way_2",
    waybillNumber: "IRS-2026-00102",
    type: "receipt",
    contactId: "cnt_2",
    contactName: "Eczacıbaşı Tüketim Ürünleri San. Tic. A.Ş.",
    contactPhone: "+90 (216) 585 80 00",
    taxNumber: "3250019283",
    waybillDate: "2026-07-25",
    dispatchDate: "2026-07-25 14:00",
    vehiclePlate: "16 ECZ 44",
    driverName: "Selim Avcı",
    deliveryAddress: "İkitelli OSB Teknopark Sk. No:8/12, Başakşehir / İstanbul",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
    items: [
      {
        id: "w_item_2",
        productId: "prod_2",
        productCode: "STK-1002",
        description: "Paslanmaz Çelik Evye Bataryası",
        quantity: 15,
        unit: "Adet",
        unitPrice: 1850,
        vatRate: 20,
        discountRate: 0,
        totalWithoutVat: 27750,
        vatAmount: 5550,
        totalWithVat: 33300,
      }
    ],
    subtotal: 27750,
    totalVat: 5550,
    grandTotal: 33300,
    currency: "₺",
    status: "delivered",
    notes: "Gelen malzemeler depoya sağlam teslim alındı.",
    createdAt: "2026-07-25",
  }
];

export const initialEmployees: Employee[] = [
  // ==========================================
  // MERKEZ GENEL MÜDÜRLÜK (br_1)
  // ==========================================
  {
    id: "emp_br1_mgr",
    tckn: "10293847562",
    fullName: "Ahmet Yılmaz",
    gender: "Erkek",
    title: "Şube Müdürü / Genel Müdür",
    department: "Yönetim",
    startDate: "2022-01-10",
    birthDate: "1985-04-12",
    homeAddress: "Mecidiyeköy Mah. Büyükdere Cad. No:195 Şişli / İstanbul",
    phone: "+90 (212) 444 0 999",
    email: "ahmet.yilmaz@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 110000,
    foodAllowance: 5000,
    roadAllowance: 3500,
    hasBes: true,
    sgkOccupationCode: "1120.01",
    iban: "TR12 0006 2000 0000 0011 2233 00",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 20,
    usedAnnualLeave: 5,
    notes: "Merkez Genel Müdürlük Şube Sorumlusu",
    createdAt: "2022-01-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },
  {
    id: "emp_1",
    tckn: "19283746510",
    fullName: "Kaan Yılmaz",
    gender: "Erkek",
    title: "Kıdemli Yazılım Mimarı",
    department: "Yazılım & IT",
    startDate: "2023-03-15",
    birthDate: "1991-05-12",
    homeAddress: "Atatürk Mah. Karanfil Sok. No:14 D:5 Kadıköy / İstanbul",
    phone: "+90 (532) 111 22 33",
    email: "kaan.yilmaz@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 85000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "2512.01",
    iban: "TR12 0006 2000 0000 0011 2233 44",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 4,
    notes: "Full-stack yazılım ekibi lideri",
    createdAt: "2023-03-15",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },
  {
    id: "emp_2",
    tckn: "28471920384",
    fullName: "Selin Aksoy",
    gender: "Kadın",
    title: "Mali İşler & Muhasebe Uzmanı",
    department: "Muhasebe & Finans",
    startDate: "2024-01-10",
    birthDate: "1995-11-20",
    homeAddress: "Mecidiyeköy Mah. Gülbahar Cad. No:45 Kat:3 Şişli / İstanbul",
    phone: "+90 (533) 222 33 44",
    email: "selin.aksoy@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 62000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "2411.02",
    iban: "TR45 0006 2000 0000 0022 3344 55",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 2,
    notes: "Maliyet muhasebesi ve e-fatura operasyon sorumlusu",
    createdAt: "2024-01-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },
  {
    id: "emp_3",
    tckn: "39482019283",
    fullName: "Burak Kaya",
    gender: "Erkek",
    title: "İnsan Kaynakları Uzmanı",
    department: "İnsan Kaynakları",
    startDate: "2024-06-01",
    birthDate: "1993-08-04",
    homeAddress: "Cevizli Mah. Bağdat Cad. No:110 Maltepe / İstanbul",
    phone: "+90 (535) 333 44 55",
    email: "burak.kaya@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 58000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "2423.01",
    iban: "TR78 0006 2000 0000 0033 4455 66",
    bankName: "Yapı Kredi",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 5,
    notes: "İşe alım ve özlük hakları sorumlusu",
    createdAt: "2024-06-01",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
  },

  // ==========================================
  // ANKARA BÖLGE MÜDÜRLÜĞÜ (br_2)
  // ==========================================
  {
    id: "emp_br2_mgr",
    tckn: "40192837465",
    fullName: "Ayşe Kaya",
    title: "Ankara Bölge Müdürü",
    department: "Yönetim",
    startDate: "2023-01-15",
    birthDate: "1987-09-22",
    homeAddress: "Kavaklıdere Tunalı Hilmi Cad. No:88 Çankaya / Ankara",
    phone: "+90 (312) 555 12 34",
    email: "ayse.kaya@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 95000,
    foodAllowance: 5000,
    roadAllowance: 3000,
    hasBes: true,
    sgkOccupationCode: "1120.02",
    iban: "TR11 0006 2000 0000 0044 1122 33",
    bankName: "VakıfBank",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 3,
    notes: "Ankara Bölge Müdürlüğü Sorumlusu",
    createdAt: "2023-01-15",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },
  {
    id: "emp_br2_staff1",
    tckn: "51203948576",
    fullName: "Merve Aydın",
    title: "Bölge Satış Uzmanı",
    department: "Satış & Pazarlama",
    startDate: "2024-03-01",
    birthDate: "1994-02-18",
    homeAddress: "Bahçelievler 7. Cadde No:42 Çankaya / Ankara",
    phone: "+90 (536) 555 66 77",
    email: "merve.aydin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 54000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "2431.01",
    iban: "TR22 0006 2000 0000 0055 2233 44",
    bankName: "Ziraat Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "Ankara ve İç Anadolu Bölgesi Kurumsal Müşteri Portföyü",
    createdAt: "2024-03-01",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },
  {
    id: "emp_br2_staff2",
    tckn: "62314059687",
    fullName: "Hakan Demir",
    title: "Müşteri İlişkileri Temsilcisi",
    department: "Müşteri Hizmetleri",
    startDate: "2024-08-10",
    birthDate: "1996-07-05",
    homeAddress: "Çayyolu Mah. 2432. Cadde No:15 Yenimahalle / Ankara",
    phone: "+90 (537) 666 77 88",
    email: "hakan.demir@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 48000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "3339.01",
    iban: "TR33 0006 2000 0000 0066 3344 55",
    bankName: "Halkbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Bölge müşteri destek ve çağrı kaydı yönetimi",
    createdAt: "2024-08-10",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },
  {
    id: "emp_br2_staff3",
    tckn: "73425160798",
    fullName: "Onur Arslan",
    title: "Bölge Operasyon Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2025-01-15",
    birthDate: "1992-12-11",
    homeAddress: "Eryaman Mah. 1. Etap No:88 Etimesgut / Ankara",
    phone: "+90 (538) 777 88 99",
    email: "onur.arslan@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 52000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "3331.02",
    iban: "TR44 0006 2000 0000 0077 4455 66",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Ankara bölge lojistik ve saha operasyon takibi",
    createdAt: "2025-01-15",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
  },

  // ==========================================
  // İZMİR ŞUBESİ (br_3)
  // ==========================================
  {
    id: "emp_br3_mgr",
    tckn: "84536271809",
    fullName: "Mehmet Demir",
    title: "İzmir Şube Müdürü",
    department: "Yönetim",
    startDate: "2023-05-01",
    birthDate: "1986-03-30",
    homeAddress: "Alsancak Atatürk Cad. No:142 Konak / İzmir",
    phone: "+90 (232) 444 88 99",
    email: "mehmet.demir@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 90000,
    foodAllowance: 5000,
    roadAllowance: 3000,
    hasBes: true,
    sgkOccupationCode: "1120.03",
    iban: "TR55 0006 2000 0000 0088 5566 77",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 2,
    notes: "İzmir Şube Sorumlusu",
    createdAt: "2023-05-01",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },
  {
    id: "emp_br3_staff1",
    tckn: "95647382910",
    fullName: "Cemal Yıldız",
    title: "Ege Bölge Saha Satış Temsilcisi",
    department: "Satış & Pazarlama",
    startDate: "2024-02-15",
    birthDate: "1993-10-14",
    homeAddress: "Mavişehir Yalı Mah. 6523. Sokak Karşıyaka / İzmir",
    phone: "+90 (539) 888 99 00",
    email: "cemal.yildiz@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 53000,
    foodAllowance: 4500,
    roadAllowance: 3000,
    hasBes: true,
    sgkOccupationCode: "2431.02",
    iban: "TR66 0006 2000 0000 0099 6677 88",
    bankName: "Akbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 3,
    notes: "Ege bölgesi bayii ve saha müşteri ilişkileri",
    createdAt: "2024-02-15",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },
  {
    id: "emp_br3_staff2",
    tckn: "10758493021",
    fullName: "Ezgi Çelik",
    title: "Şube Ön Muhasebe Elemanı",
    department: "Muhasebe & Finans",
    startDate: "2024-07-01",
    birthDate: "1997-06-25",
    homeAddress: "Göztepe Mah. Mithatpaşa Cad. No:210 Konak / İzmir",
    phone: "+90 (540) 999 00 11",
    email: "ezgi.celik@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 46000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "4311.01",
    iban: "TR77 0006 2000 0000 0011 7788 99",
    bankName: "Yapı Kredi",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "İzmir şubesi kasa, fatura ve cari hesap mutabakatları",
    createdAt: "2024-07-01",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },
  {
    id: "emp_br3_staff3",
    tckn: "21869504132",
    fullName: "Tolga Şahin",
    title: "Lojistik & Müşteri Hizmetleri",
    department: "Müşteri Hizmetleri",
    startDate: "2025-02-01",
    birthDate: "1995-01-08",
    homeAddress: "Bornova Küçükpark Mah. 162. Sokak No:12 Bornova / İzmir",
    phone: "+90 (541) 000 11 22",
    email: "tolga.sahin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 47000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "3339.02",
    iban: "TR88 0006 2000 0000 0022 8899 00",
    bankName: "DenizBank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "İzmir şubesi sevkiyat bilgilendirme ve müşteri ilişkileri",
    createdAt: "2025-02-01",
    branchId: "br_3",
    branchName: "İzmir Şubesi",
  },

  // ==========================================
  // GEBZE LOJİSTİK & ANA DEPO (wh_1)
  // ==========================================
  {
    id: "emp_wh1_mgr",
    tckn: "32970615243",
    fullName: "Hasan Öztürk",
    title: "Ana Depo Müdürü / Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2023-02-10",
    birthDate: "1984-07-19",
    homeAddress: "Güzeller Mah. OSB 2. Cadde No:15 Gebze / Kocaeli",
    phone: "+90 (262) 644 11 22",
    email: "hasan.ozturk@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 68000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "1324.01",
    iban: "TR99 0006 2000 0000 0033 9900 11",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 4,
    notes: "Gebze Lojistik Ana Depo Sorumlusu",
    createdAt: "2023-02-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },
  {
    id: "emp_wh1_staff1",
    tckn: "43081726354",
    fullName: "Ahmet Tunç",
    title: "Depo Mal Kabul Operatörü",
    department: "Operasyon & Lojistik",
    startDate: "2024-04-01",
    birthDate: "1996-09-12",
    homeAddress: "İnönü Mah. Gençlik Cad. No:34 Gebze / Kocaeli",
    phone: "+90 (542) 111 22 33",
    email: "ahmet.tunc@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 42000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "4321.01",
    iban: "TR10 0006 2000 0000 0044 0011 22",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 2,
    notes: "Tedarikçi teslimatı mal kabul ve barkodlama",
    createdAt: "2024-04-01",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },
  {
    id: "emp_wh1_staff2",
    tckn: "54192837465",
    fullName: "Mustafa Erdem",
    title: "Forklift & İstif Operatörü",
    department: "Operasyon & Lojistik",
    startDate: "2024-09-15",
    birthDate: "1992-11-03",
    homeAddress: "Mustafapaşa Mah. Bağdat Cad. No:78 Gebze / Kocaeli",
    phone: "+90 (543) 222 33 44",
    email: "mustafa.erdem@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 44000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "8334.01",
    iban: "TR21 0006 2000 0000 0055 1122 33",
    bankName: "Ziraat Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "Sertifikalı ağır istif ve raflama operatörü",
    createdAt: "2024-09-15",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },
  {
    id: "emp_wh1_staff3",
    tckn: "65203948576",
    fullName: "Emre Kılıç",
    title: "Stok & Envanter Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2025-01-10",
    birthDate: "1994-05-28",
    homeAddress: "Arapçeşme Mah. 1022. Sokak No:5 Darıca / Kocaeli",
    phone: "+90 (544) 333 44 55",
    email: "emre.kilic@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 46000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "4321.02",
    iban: "TR32 0006 2000 0000 0066 2233 44",
    bankName: "Yapı Kredi",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Periyodik depo sayımı ve kayıp/kaçak kontrolü",
    createdAt: "2025-01-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
  },

  // ==========================================
  // İKİTELLİ YEDEK PARÇA DEPOSU (wh_2)
  // ==========================================
  {
    id: "emp_wh2_mgr",
    tckn: "76314059687",
    fullName: "Ali Can",
    title: "Yedek Parça Depo Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2023-04-12",
    birthDate: "1988-12-04",
    homeAddress: "İkitelli OSB Teknopark Sk. No:8/12 Başakşehir / İstanbul",
    phone: "+90 (212) 549 00 11",
    email: "ali.can@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 65000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "1324.02",
    iban: "TR43 0006 2000 0000 0077 3344 55",
    bankName: "Akbank",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 3,
    notes: "İkitelli Yedek Parça Depo Sorumlusu",
    createdAt: "2023-04-12",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },
  {
    id: "emp_wh2_staff1",
    tckn: "87425160798",
    fullName: "Tarık Şahin",
    title: "Yedek Parça Sayım Elemanı",
    department: "Operasyon & Lojistik",
    startDate: "2024-05-15",
    birthDate: "1997-03-17",
    homeAddress: "Halkalı Merkez Mah. Dereboyu Cad. No:44 Küçükçekmece / İstanbul",
    phone: "+90 (545) 444 55 66",
    email: "tarik.sahin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 41000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "4321.03",
    iban: "TR54 0006 2000 0000 0088 4455 66",
    bankName: "QNB Finansbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 2,
    notes: "Otomotiv ve makine yedek parça kodlama takibi",
    createdAt: "2024-05-15",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },
  {
    id: "emp_wh2_staff2",
    tckn: "98536271809",
    fullName: "Serkan Yalçın",
    title: "Paketleme & Etiketleme Elemanı",
    department: "Operasyon & Lojistik",
    startDate: "2024-10-01",
    birthDate: "1999-08-22",
    homeAddress: "Mehmet Akif Mah. Aşık Veysel Cad. No:19 Küçükçekmece / İstanbul",
    phone: "+90 (546) 555 66 77",
    email: "serkan.yalcin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 40000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "9329.01",
    iban: "TR65 0006 2000 0000 0099 5566 77",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Kargo ve kurye paketleme ve etiket basım alanı",
    createdAt: "2024-10-01",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },
  {
    id: "emp_wh2_staff3",
    tckn: "10947382910",
    fullName: "Murat Yıldırım",
    title: "Sipariş Hazırlama Operatörü",
    department: "Operasyon & Lojistik",
    startDate: "2025-02-10",
    birthDate: "1995-04-14",
    homeAddress: "Ziya Gökalp Mah. Hürriyet Bulvarı No:90 Başakşehir / İstanbul",
    phone: "+90 (547) 666 77 88",
    email: "murat.yildirim@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 43000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "4321.04",
    iban: "TR76 0006 2000 0000 0010 6677 88",
    bankName: "İş Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "E-ticaret ve bayii sipariş toplama / toplama listesi operasyonu",
    createdAt: "2025-02-10",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
  },

  // ==========================================
  // ANKARA LOJİSTİK TRANSİT DEPO (wh_3)
  // ==========================================
  {
    id: "emp_wh3_mgr",
    tckn: "21058493021",
    fullName: "Selin Şahin",
    title: "Transit Depo Sorumlusu",
    department: "Operasyon & Lojistik",
    startDate: "2023-06-01",
    birthDate: "1989-10-08",
    homeAddress: "Ostim 100. Yıl Bulvarı No:45/2 Yenimahalle / Ankara",
    phone: "+90 (312) 395 77 88",
    email: "selin.sahin@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 63000,
    foodAllowance: 4500,
    roadAllowance: 2500,
    hasBes: true,
    sgkOccupationCode: "1324.03",
    iban: "TR87 0006 2000 0000 0021 7788 99",
    bankName: "VakıfBank",
    status: "active",
    annualLeaveAllowance: 18,
    usedAnnualLeave: 2,
    notes: "Ankara Lojistik Transit Depo Sorumlusu",
    createdAt: "2023-06-01",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
  {
    id: "emp_wh3_staff1",
    tckn: "32169504132",
    fullName: "Deniz Güneş",
    title: "Transit Sevkiyat Koordinatörü",
    department: "Operasyon & Lojistik",
    startDate: "2024-06-15",
    birthDate: "1994-01-30",
    homeAddress: "Macun Mah. Bağdat Cad. No:112 Yenimahalle / Ankara",
    phone: "+90 (548) 777 88 99",
    email: "deniz.gunes@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 45000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "3331.03",
    iban: "TR98 0006 2000 0000 0032 8899 00",
    bankName: "Ziraat Bankası",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 1,
    notes: "Şehirlerarası tır ve araç sevk planlaması",
    createdAt: "2024-06-15",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
  {
    id: "emp_wh3_staff2",
    tckn: "43270615243",
    fullName: "Onur Şimşek",
    title: "Saha & Yükleme Elemanı",
    department: "Operasyon & Lojistik",
    startDate: "2024-11-10",
    birthDate: "1998-07-21",
    homeAddress: "Şentepe Mah. Seval Cad. No:83 Yenimahalle / Ankara",
    phone: "+90 (549) 888 99 00",
    email: "onur.simsek@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 41000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: false,
    sgkOccupationCode: "9333.01",
    iban: "TR09 0006 2000 0000 0043 9900 11",
    bankName: "Halkbank",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "Transit araç yükleme ve boşaltma operasyonu",
    createdAt: "2024-11-10",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
  {
    id: "emp_wh3_staff3",
    tckn: "54381726354",
    fullName: "Elif Bozkurt",
    title: "Depo Giriş/Çıkış Kayıt Görevlisi",
    department: "Operasyon & Lojistik",
    startDate: "2025-01-20",
    birthDate: "1996-12-02",
    homeAddress: "Batıkent Kentkoop Mah. 1868. Sokak No:24 Yenimahalle / Ankara",
    phone: "+90 (550) 999 00 11",
    email: "elif.bozkurt@muavin.com.tr",
    salaryType: "net",
    salaryAmount: 42000,
    foodAllowance: 4500,
    roadAllowance: 2000,
    hasBes: true,
    sgkOccupationCode: "4321.05",
    iban: "TR10 0006 2000 0000 0054 0011 22",
    bankName: "Garanti BBVA",
    status: "active",
    annualLeaveAllowance: 14,
    usedAnnualLeave: 0,
    notes: "İrsaliye ve transit irsaliye giriş-çıkış evrak takibi",
    createdAt: "2025-01-20",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    warehouseId: "wh_3",
    warehouseName: "Ankara Lojistik Transit Depo",
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "lv_1",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    type: "Yıllık İzin",
    startDate: "2026-08-10",
    endDate: "2026-08-14",
    daysCount: 5,
    status: "approved",
    reason: "Yaz dönemi yıllık izin kullanımı",
    createdAt: "2026-07-20",
  },
  {
    id: "lv_2",
    employeeId: "emp_2",
    employeeName: "Selin Aksoy",
    type: "Sıhhi İzin",
    startDate: "2026-07-15",
    endDate: "2026-07-18",
    daysCount: 4,
    status: "approved",
    reason: "Doktor raporlu sıhhi izin (2 günü aşan 2 gün maaştan kesilir)",
    createdAt: "2026-07-14",
  },
  {
    id: "lv_3",
    employeeId: "emp_3",
    employeeName: "Emre Öztürk",
    type: "Ücretsiz İzin",
    startDate: "2026-07-01",
    endDate: "2026-07-03",
    daysCount: 3,
    status: "approved",
    reason: "Kişisel işler nedeniyle ücretsiz izin (Maaştan kesilir)",
    createdAt: "2026-06-28",
  },
  {
    id: "lv_4",
    employeeId: "emp_4",
    employeeName: "Zeynep Kaya",
    type: "Mazeretsiz İzin",
    startDate: "2026-07-10",
    endDate: "2026-07-10",
    daysCount: 1,
    status: "approved",
    reason: "Mazeretsiz işe gelmeme / Devamsızlık (Maaştan kesilir)",
    createdAt: "2026-07-10",
  },
  {
    id: "lv_5",
    employeeId: "emp_5",
    employeeName: "Burak Demir",
    type: "Ücretli İzin",
    startDate: "2026-07-28",
    endDate: "2026-07-28",
    daysCount: 1,
    status: "pending",
    reason: "İdari resmi randevu ücretli izni",
    createdAt: "2026-07-24",
  },
  {
    id: "lv_6",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    type: "Babalık İzni (Erkek Doğum İzni)",
    startDate: "2026-06-15",
    endDate: "2026-06-19",
    daysCount: 5,
    status: "approved",
    reason: "4857 Sayılı İş Kanunu Ek Md. 2 Uyarınca Eşi Doğum Yapan Erkek Personel Babalık İzni",
    createdAt: "2026-06-15",
  },
];

export const initialAdvanceRequests: AdvanceRequest[] = [
  {
    id: "adv_1",
    employeeId: "emp_3",
    employeeName: "Emre Öztürk",
    type: "Masraf",
    amount: 3450,
    requestDate: "2026-07-22",
    description: "Ankara Müşteri Ziyareti - Hızlı Tren ve Otel Konaklama",
    status: "paid",
    createdAt: "2026-07-22",
  },
  {
    id: "adv_2",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    type: "Avans",
    amount: 15000,
    requestDate: "2026-07-24",
    description: "Maaş öncesi kısıtlı avans talebi",
    status: "pending",
    createdAt: "2026-07-24",
  },
];

export const initialLegalDeductions: LegalDeduction[] = [
  {
    id: "leg_1",
    employeeId: "emp_1", // Kaan Yılmaz
    employeeName: "Kaan Yılmaz",
    type: "İcra Kesintisi",
    fileNumber: "İstanbul 8. İcra Dairesi 2025/11204 Esas",
    creditorName: "Garanti BBVA A.Ş. Vekili",
    iban: "TR12 0006 2000 0000 0011 2233 44",
    totalDebtAmount: 60000,
    paidAmount: 25000,
    monthlyAmount: 8750,
    calculationType: "quarter_salary",
    priorityOrder: 1,
    status: "active",
    notes: "1. Sıradaki aktif icra dosyası. Maaşının 1/4'ü oranında kesinti yapılıyor.",
    createdAt: "2025-11-10",
  },
  {
    id: "leg_2",
    employeeId: "emp_1", // Kaan Yılmaz - 2. İcra dosyası (Sırada Bekliyor!)
    employeeName: "Kaan Yılmaz",
    type: "İcra Kesintisi",
    fileNumber: "Ankara 3. İcra Dairesi 2026/4582 Esas",
    creditorName: "Yapı Kredi Bankası A.Ş.",
    iban: "TR45 0006 7000 0000 0055 6677 88",
    totalDebtAmount: 40000,
    paidAmount: 0,
    monthlyAmount: 7500,
    calculationType: "fixed",
    priorityOrder: 2,
    status: "queued",
    notes: "2. Sıradaki icra dosyası. 1. Sıradaki borç bittiğinde otomatik aktifleşir.",
    createdAt: "2026-02-15",
  },
  {
    id: "leg_3",
    employeeId: "emp_2", // Selin Aksoy - Nafaka Kesintisi
    employeeName: "Selin Aksoy",
    type: "Nafaka Kesintisi",
    fileNumber: "Kadıköy 2. Aile Mahkemesi 2024/912 Esas",
    creditorName: "Ahmet Aksoy (Çocuk Nafakası)",
    iban: "TR98 0001 5000 0000 0099 8877 66",
    totalDebtAmount: 0, // Sürekli / Aylık nafaka
    paidAmount: 36000,
    monthlyAmount: 6000,
    calculationType: "fixed",
    priorityOrder: 1,
    status: "active",
    notes: "Aylık ilamlı çocuk nafaka kesintisi.",
    createdAt: "2024-05-01",
  },
];

export const initialOrders: Order[] = [
  {
    id: "ord_1",
    orderNumber: "SIP-2026-00001",
    type: "sales",
    contactId: "c1",
    contactName: "TeknoPark Teknoloji A.Ş.",
    contactPhone: "+90 (212) 555 01 23",
    contactEmail: "siparis@teknopark.com.tr",
    taxNumber: "8470291038",
    orderDate: "2026-07-20",
    deliveryDate: "2026-07-30",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
    items: [
      {
        id: "ord_item_1",
        productId: "p1",
        productCode: "STK-001",
        description: "Dell XPS 15 Dizüstü Bilgisayar (i7/32GB/1TB)",
        quantity: 3,
        unit: "Adet",
        unitPrice: 45000,
        vatRate: 20,
        totalWithoutVat: 135000,
        vatAmount: 27000,
        totalWithVat: 162000,
      },
      {
        id: "ord_item_2",
        productId: "p2",
        productCode: "STK-002",
        description: "LG 27 inç 4K UHD Monitör",
        quantity: 5,
        unit: "Adet",
        unitPrice: 9500,
        vatRate: 20,
        totalWithoutVat: 47500,
        vatAmount: 9500,
        totalWithVat: 57000,
      },
    ],
    subtotal: 182500,
    totalVat: 36500,
    grandTotal: 219000,
    currency: "₺",
    status: "approved",
    notes: "Sevkiyat Gebze lojistik ana depodan yapılacaktır. Ödeme teslimatta %50 peşin.",
    createdAt: "2026-07-20",
  },
  {
    id: "ord_2",
    orderNumber: "SIP-2026-00002",
    type: "purchase",
    contactId: "c2",
    contactName: "Beta Lojistik ve Taşımacılık Ltd. Şti.",
    contactPhone: "+90 (212) 444 02 44",
    contactEmail: "tedarik@betalojistik.com.tr",
    taxNumber: "1920384756",
    orderDate: "2026-07-22",
    deliveryDate: "2026-08-05",
    warehouseId: "wh_2",
    warehouseName: "İkitelli Yedek Parça Deposu",
    items: [
      {
        id: "ord_item_3",
        productId: "p3",
        productCode: "STK-003",
        description: "Logitech MX Master 3S Kablosuz Fare",
        quantity: 20,
        unit: "Adet",
        unitPrice: 3200,
        vatRate: 20,
        totalWithoutVat: 64000,
        vatAmount: 12800,
        totalWithVat: 76800,
      },
    ],
    subtotal: 64000,
    totalVat: 12800,
    grandTotal: 76800,
    currency: "₺",
    status: "pending",
    notes: "İkitelli şubesine doğrudan teslimat bekleniyor.",
    createdAt: "2026-07-22",
  },
  {
    id: "ord_3",
    orderNumber: "SIP-2026-00003",
    type: "sales",
    contactId: "c3",
    contactName: "Gama Medya Danışmanlık A.Ş.",
    contactPhone: "+90 (216) 333 44 55",
    contactEmail: "satinalma@gamamedya.com",
    taxNumber: "9870123456",
    orderDate: "2026-07-15",
    deliveryDate: "2026-07-25",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
    items: [
      {
        id: "ord_item_4",
        productId: "srv_1",
        productCode: "HZ-001",
        description: "Kurumsal Bulut Danışmanlık ve Yazılım Desteği (Aylık)",
        quantity: 1,
        unit: "Ay",
        unitPrice: 50000,
        vatRate: 20,
        totalWithoutVat: 50000,
        vatAmount: 10000,
        totalWithVat: 60000,
      },
    ],
    subtotal: 50000,
    totalVat: 10000,
    grandTotal: 60000,
    currency: "₺",
    status: "converted",
    convertedToInvoiceId: "inv_sales_001",
    convertedToInvoiceNumber: "GIB20260000045",
    notes: "Sipariş tamamlandı ve Fatura GIB20260000045 olarak kesildi.",
    createdAt: "2026-07-15",
  },
];

export const initialCostProjects: CostProject[] = [
  {
    id: "prj_001",
    code: "PRJ-2026-001",
    name: "Maslak Plaza İç Mimari & Şantiye Uygulama",
    category: "İnşaat / Taahhüt",
    contactId: "c1",
    contactName: "TeknoHolding A.Ş.",
    startDate: "2026-02-01",
    endDate: "2026-08-30",
    budget: 450000,
    contractPrice: 680000,
    status: "active",
    description: "Maslak Plaza B Blok 5. Kat mekanik, elektrik ve dekorasyon maliyet takibi.",
    createdAt: "2026-02-01",
    costItems: [
      {
        id: "pitem_1",
        type: "material",
        description: "Granit Seramik & Yapıştırıcı Sarf Malzemeleri",
        quantity: 350,
        unit: "m²",
        unitCost: 420,
        totalCost: 147000,
        date: "2026-02-15",
        notes: "60x120 Lüks granit"
      },
      {
        id: "pitem_2",
        type: "subcontractor",
        description: "Elektrik & Zayıf Akım Tesisatı Taşeron Ödemesi",
        quantity: 1,
        unit: "Hizmet",
        unitCost: 85000,
        totalCost: 85000,
        date: "2026-03-01"
      },
      {
        id: "pitem_3",
        type: "labor",
        description: "Saha Usta ve İşçilik Yevmiyeleri (Şubat-Mart)",
        quantity: 45,
        unit: "Adam/Gün",
        unitCost: 1800,
        totalCost: 81000,
        date: "2026-03-15"
      }
    ]
  },
  {
    id: "prj_002",
    code: "PRJ-2026-002",
    name: "E-Ticaret & Lojistik Mobil Uygulama",
    category: "Yazılım / Ar-Ge",
    contactId: "c2",
    contactName: "Atlas Lojistik A.Ş.",
    startDate: "2026-03-10",
    endDate: "2026-09-15",
    budget: 220000,
    contractPrice: 340000,
    status: "active",
    description: "iOS ve Android sürücü takip ve sipariş yönetim mobil yazılım projesi.",
    createdAt: "2026-03-10",
    costItems: [
      {
        id: "pitem_4",
        type: "labor",
        description: "Senior Mobil Yazılım Uzmanı Adam/Ay",
        quantity: 2,
        unit: "Ay",
        unitCost: 65000,
        totalCost: 130000,
        date: "2026-04-01"
      },
      {
        id: "pitem_5",
        type: "overhead",
        description: "AWS Bulut Altyapısı & Harita API Lisansları",
        quantity: 1,
        unit: "Paket",
        unitCost: 24000,
        totalCost: 24000,
        date: "2026-04-10"
      }
    ]
  }
];

export const initialAssetCustodies: AssetCustody[] = [
  // 1. ARAÇ ZİMMETLERİ (VEHICLES)
  {
    id: "zim_veh_001",
    employeeId: "emp_br2_mgr",
    employeeName: "Ayşe Kaya",
    employeeDepartment: "Yönetim",
    employeeTitle: "Ankara Bölge Müdürü",
    category: "vehicle",
    assetName: "2024 Renault Megane Touch 1.3 TCe EDC",
    brand: "Renault",
    model: "Megane IV Touch 140 HP EDC",
    barcodeNumber: "ZIM-2026-ARC-01",
    inventoryNumber: "DMB-ARC-001",
    assignedDate: "2024-02-15",
    status: "active",
    conditionOnDelivery: "new",
    approximateValue: 1380000,
    currency: "₺",
    notes: "Ankara Bölge Müdürlüğü makam ve müşteri ziyaret aracı olarak teslim edilmiştir.",
    createdAt: "2024-02-15",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    vehicleDetails: {
      plateNumber: "06 MAV 195",
      chassisNumber: "VF1RFB00469201948",
      engineNumber: "H5HT470A09281",
      fuelType: "Benzin",
      currentKm: 18450,
      insuranceExpiryDate: "2027-02-15",
      kaskoExpiryDate: "2027-02-15",
      inspectionExpiryDate: "2027-02-10",
      fuelCardNumber: "OPET-OTOBIL-849201",
      hgsNumber: "HGS-06-8492018",
      hasSpareKey: true,
      hasLicenseCard: true,
      hasTrafficSet: true,
    },
    accessoriesList: ["Yedek Anahtar", "Orijinal Trafik Seti & Yangın Söndürücü", "Stepne & Kriko", "Ruhsat & Sigorta Poliçesi", "Opet Taşıt Tanıma Kartı"],
  },
  {
    id: "zim_veh_002",
    employeeId: "emp_wh1_driver",
    employeeName: "Mehmet Can",
    employeeDepartment: "Operasyon & Lojistik",
    employeeTitle: "Kıdemli Sevkiyat & Dağıtım Şoförü",
    category: "vehicle",
    assetName: "2023 Ford Transit Custom 320L Panelvan",
    brand: "Ford",
    model: "Transit Custom 2.0 EcoBlue 130PS",
    barcodeNumber: "ZIM-2026-ARC-02",
    inventoryNumber: "DMB-ARC-002",
    assignedDate: "2023-08-01",
    status: "active",
    conditionOnDelivery: "excellent",
    approximateValue: 1150000,
    currency: "₺",
    notes: "Marmara Bölgesi müşteri sevkiyat ve depo transferleri lojistik aracı.",
    createdAt: "2023-08-01",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
    vehicleDetails: {
      plateNumber: "34 MAV 840",
      chassisNumber: "WF0YXXTTGYPK92019",
      engineNumber: "BKFA109284",
      fuelType: "Dizel",
      currentKm: 52300,
      insuranceExpiryDate: "2026-11-20",
      kaskoExpiryDate: "2026-11-20",
      inspectionExpiryDate: "2026-10-15",
      fuelCardNumber: "SHELL-TTS-948201",
      hgsNumber: "HGS-34-9201847",
      hasSpareKey: true,
      hasLicenseCard: true,
      hasTrafficSet: true,
    },
    accessoriesList: ["Yedek Anahtar", "Yük Sabitleme Kayışları (4 Adet)", "Trafik Seti & Yangın Tüpü", "Takoz & Kriko", "Shell Taşıt Tanıma Çipi"],
  },

  // 2. BİLGİSAYAR & LAPTOP ZİMMETLERİ (COMPUTERS)
  {
    id: "zim_pc_001",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    employeeDepartment: "Yazılım & IT",
    employeeTitle: "Kıdemli Yazılım Mimarı",
    category: "computer",
    assetName: "Apple MacBook Pro 16\" M3 Max",
    brand: "Apple",
    model: "MacBook Pro 16\" Space Black (36GB RAM / 1TB SSD)",
    serialNumber: "C02G4029MD6R",
    barcodeNumber: "ZIM-2026-PC-01",
    inventoryNumber: "DMB-BILG-001",
    assignedDate: "2024-01-05",
    status: "active",
    conditionOnDelivery: "new",
    approximateValue: 145000,
    currency: "₺",
    notes: "Yazılım mimarisi ve bulut sistem geliştirme için tahsis edilmiştir.",
    createdAt: "2024-01-05",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    computerDetails: {
      computerType: "laptop",
      processor: "Apple M3 Max (14 Çekirdek CPU, 30 Çekirdek GPU)",
      ram: "36 GB Birleşik Bellek",
      storage: "1 TB NVMe SSD",
      operatingSystem: "macOS Sonoma (14.5)",
      macAddress: "3C:22:FB:4A:8C:91",
      screenSize: "16.2 inç Liquid Retina XDR",
      includesCharger: true,
      includesBag: true,
      includesMouse: true,
      includesLock: false,
    },
    accessoriesList: ["140W USB-C Güç Adaptörü", "Örgülü MagSafe 3 Kablosu", "Tucano 16\" Su Geçirmez Sırt Çantası", "Apple Magic Mouse 2 (Black)"],
  },
  {
    id: "zim_pc_002",
    employeeId: "emp_2",
    employeeName: "Selin Aksoy",
    employeeDepartment: "Muhasebe & Finans",
    employeeTitle: "Mali İşler & Muhasebe Uzmanı",
    category: "computer",
    assetName: "Dell XPS 15 9530 Core i7-13700H",
    brand: "Dell",
    model: "XPS 15 9530 (32GB RAM / 1TB SSD / RTX 4060)",
    serialNumber: "8F9G2H3-DELL-TR",
    barcodeNumber: "ZIM-2026-PC-02",
    inventoryNumber: "DMB-BILG-002",
    assignedDate: "2024-01-15",
    status: "active",
    conditionOnDelivery: "new",
    approximateValue: 88000,
    currency: "₺",
    notes: "Ön muhasebe, mali mizan ve e-fatura operasyonları için tahsis edilmiştir.",
    createdAt: "2024-01-15",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    computerDetails: {
      computerType: "laptop",
      processor: "Intel Core i7-13700H (14 Çekirdek 5.0 GHz)",
      ram: "32 GB DDR5 5200MHz",
      storage: "1 TB PCIe 4.0 NVMe SSD",
      operatingSystem: "Windows 11 Pro Lisanslı",
      macAddress: "94:E6:F7:1B:32:04",
      screenSize: "15.6 inç OLED 3.5K Dokunmatik",
      includesCharger: true,
      includesBag: true,
      includesMouse: true,
      includesLock: true,
    },
    accessoriesList: ["130W Type-C Orijinal Adaptör", "Dell Premier Omuz Çantası", "Logitech MX Master 3S Kablosuz Fare", "Kensington Kilit"],
  },
  {
    id: "zim_pc_003",
    employeeId: "emp_3",
    employeeName: "Burak Kaya",
    employeeDepartment: "İnsan Kaynakları",
    employeeTitle: "İnsan Kaynakları Uzmanı",
    category: "computer",
    assetName: "Lenovo ThinkPad T14 Gen 4 Ryzen 7 PRO",
    brand: "Lenovo",
    model: "ThinkPad T14 Gen 4 (32GB RAM / 512GB SSD)",
    serialNumber: "PF3Z9X8K-LNV",
    barcodeNumber: "ZIM-2026-PC-03",
    inventoryNumber: "DMB-BILG-003",
    assignedDate: "2024-06-02",
    status: "active",
    conditionOnDelivery: "excellent",
    approximateValue: 56000,
    currency: "₺",
    notes: "İnsan kaynakları ve bordro hazırlama işlemleri için tahsis edilmiştir.",
    createdAt: "2024-06-02",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    computerDetails: {
      computerType: "laptop",
      processor: "AMD Ryzen 7 PRO 7840U (8 Çekirdek)",
      ram: "32 GB LPDDR5x",
      storage: "512 GB NVMe SSD",
      operatingSystem: "Windows 11 Pro",
      macAddress: "50:EB:71:A2:89:11",
      screenSize: "14 inç WUXGA IPS Mat Ekran",
      includesCharger: true,
      includesBag: true,
      includesMouse: true,
      includesLock: false,
    },
    accessoriesList: ["65W GaN Type-C Şarj Aleti", "ThinkPad Taşıma Çantası", "Lenovo Silent Kablosuz Mouse"],
  },

  // 3. CEP TELEFONU ZİMMETLERİ (PHONES)
  {
    id: "zim_ph_001",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    employeeDepartment: "Yazılım & IT",
    employeeTitle: "Kıdemli Yazılım Mimarı",
    category: "phone",
    assetName: "Apple iPhone 15 Pro 256GB Titanyum",
    brand: "Apple",
    model: "iPhone 15 Pro 256GB Natural Titanium",
    serialNumber: "DX49K20PL891",
    barcodeNumber: "ZIM-2026-TEL-01",
    inventoryNumber: "DMB-TEL-001",
    assignedDate: "2024-01-08",
    status: "active",
    conditionOnDelivery: "new",
    approximateValue: 72000,
    currency: "₺",
    notes: "Kurumsal hat ve 2FA yetkilendirme amacıyla tahsis edilmiştir.",
    createdAt: "2024-01-08",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    phoneDetails: {
      imei1: "358492019482019",
      imei2: "358492019482020",
      phoneNumber: "+90 (532) 111 22 33",
      simCardNumber: "899001029482019284",
      storageCapacity: "256 GB",
      color: "Natürel Titanyum",
      includesCharger: true,
      includesHeadphones: false,
      includesCaseScreenProtector: true,
    },
    accessoriesList: ["Orijinal USB-C Örgülü Kablo", "20W Apple USB-C Hızlı Şarj Adaptörü", "Spigen MagSafe Şeffaf Kılıf", "Temperli Cam Ekran Koruyucu"],
  },
  {
    id: "zim_ph_002",
    employeeId: "emp_br2_mgr",
    employeeName: "Ayşe Kaya",
    employeeDepartment: "Yönetim",
    employeeTitle: "Ankara Bölge Müdürü",
    category: "phone",
    assetName: "Samsung Galaxy S24 Ultra 512GB",
    brand: "Samsung",
    model: "Galaxy S24 Ultra Titanium Black (12GB/512GB)",
    serialNumber: "R5CW2094K8Z",
    barcodeNumber: "ZIM-2026-TEL-02",
    inventoryNumber: "DMB-TEL-002",
    assignedDate: "2024-02-16",
    status: "active",
    conditionOnDelivery: "new",
    approximateValue: 78000,
    currency: "₺",
    notes: "Ankara bölge yönetimi ve müşteri iletişim hattı.",
    createdAt: "2024-02-16",
    branchId: "br_2",
    branchName: "Ankara Bölge Müdürlüğü",
    phoneDetails: {
      imei1: "359102948571029",
      imei2: "359102948571030",
      phoneNumber: "+90 (312) 555 12 34",
      simCardNumber: "899001093847291048",
      storageCapacity: "512 GB",
      color: "Titanyum Siyah",
      includesCharger: true,
      includesHeadphones: true,
      includesCaseScreenProtector: true,
    },
    accessoriesList: ["45W Süper Hızlı Şarj Adaptörü", "Type-C to Type-C 5A Kablo", "Deri Kapaklı Orijinal Kılıf", "S-Pen (Dahili)"],
  },

  // 4. TABLET & IPAD ZİMMETLERİ (TABLETS)
  {
    id: "zim_tab_001",
    employeeId: "emp_1",
    employeeName: "Kaan Yılmaz",
    employeeDepartment: "Yazılım & IT",
    employeeTitle: "Kıdemli Yazılım Mimarı",
    category: "tablet",
    assetName: "Apple iPad Pro 11\" M4 256GB Wi-Fi",
    brand: "Apple",
    model: "iPad Pro 11 inç Ultra Retina XDR (M4)",
    serialNumber: "DLX9302MK189",
    barcodeNumber: "ZIM-2026-TAB-01",
    inventoryNumber: "DMB-TAB-001",
    assignedDate: "2024-05-20",
    status: "active",
    conditionOnDelivery: "new",
    approximateValue: 54000,
    currency: "₺",
    notes: "Sistem tasarımı, mimari diyagramlar ve sunumlar için tahsis edilmiştir.",
    createdAt: "2024-05-20",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    tabletDetails: {
      tabletType: "Apple iPad Pro M4",
      screenSize: "11 inç OLED Ultra Retina XDR",
      hasCellular: false,
      storageCapacity: "256 GB",
      includesStylus: true,
      includesKeyboardCase: true,
      includesCharger: true,
    },
    accessoriesList: ["Apple Pencil Pro (Haptic & Squeeze)", "Apple Magic Keyboard 11\"", "20W USB-C Güç Adaptörü & Örgülü Kablo"],
  },
  {
    id: "zim_tab_002",
    employeeId: "emp_wh1_mgr",
    employeeName: "Ahmet Yıldız",
    employeeDepartment: "Operasyon & Lojistik",
    employeeTitle: "Gebze Depo Müdürü",
    category: "tablet",
    assetName: "Samsung Galaxy Tab S9 FE+ 12.4\" Wi-Fi",
    brand: "Samsung",
    model: "Galaxy Tab S9 FE+ (8GB/128GB)",
    serialNumber: "R58X109482M",
    barcodeNumber: "ZIM-2026-TAB-02",
    inventoryNumber: "DMB-TAB-002",
    assignedDate: "2024-03-10",
    status: "active",
    conditionOnDelivery: "excellent",
    approximateValue: 24000,
    currency: "₺",
    notes: "Gebze ana depo stok sayım, barkod okuma ve irsaliye kontrol tableti.",
    createdAt: "2024-03-10",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
    tabletDetails: {
      tabletType: "Samsung Galaxy Tab S9 FE+",
      screenSize: "12.4 inç 90Hz WQXGA",
      hasCellular: false,
      storageCapacity: "128 GB",
      includesStylus: true,
      includesKeyboardCase: false,
      includesCharger: true,
    },
    accessoriesList: ["S-Pen Dokunmatik Kalem", "Darbeye Dayanıklı Zırhlı Kılıf", "Orijinal Şarj Başlığı ve Kablo"],
  },

  // 5. ÇEVRE BİRİMİ & DONANIM DEMİRBAŞI
  {
    id: "zim_per_001",
    employeeId: "emp_2",
    employeeName: "Selin Aksoy",
    employeeDepartment: "Muhasebe & Finans",
    employeeTitle: "Mali İşler & Muhasebe Uzmanı",
    category: "peripheral",
    assetName: "Dell UltraSharp 27\" 4K USB-C Hub Monitör U2723QE",
    brand: "Dell",
    model: "UltraSharp U2723QE IPS Black 4K",
    serialNumber: "CN-0F9G2H-72872",
    barcodeNumber: "ZIM-2026-MON-01",
    inventoryNumber: "DMB-MON-001",
    assignedDate: "2024-01-16",
    status: "active",
    conditionOnDelivery: "new",
    approximateValue: 32000,
    currency: "₺",
    notes: "Merkez Genel Müdürlük Muhasebe Ofisi çalışma masası monitörü.",
    createdAt: "2024-01-16",
    branchId: "br_1",
    branchName: "Merkez Genel Müdürlük",
    accessoriesList: ["Orijinal Yüksekliği Ayarlanabilir Ayak", "Thunderbolt 4 / USB-C Kablosu", "HDMI & DisplayPort Kablosu", "Güç Kablosu"],
  },
];

// ==========================================
// 🏭 ÜRETİM & MES / MRP BAŞLANGIÇ VERİLERİ
// ==========================================

export const initialWorkstations: Workstation[] = [
  {
    id: "ws_cnc_laser",
    code: "WS-LASER-01",
    name: "Fiber Lazer Kesim & Punch CNC",
    category: "cnc",
    hourlyOperatingCost: 450,
    hourlyDepreciationCost: 320,
    standardCapacityHoursPerDay: 16,
    efficiencyRate: 0.92,
    status: "running",
    currentWorkOrderId: "wo_001",
    currentWorkOrderNumber: "WO-2026-00101",
    assignedOperatorName: "Murat Demir (Kıdemli CNC Operatörü)",
    branchId: "br_1",
    branchName: "Merkez Fabrika / Üretim Tesisi",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
    notes: "4kW Yüksek Hassasiyetli Trumpf Fiber Lazer Tezgahı",
    maintenanceSchedule: {
      lastMaintenanceDate: "2026-07-15",
      nextMaintenanceDate: "2026-10-15",
    },
  },
  {
    id: "ws_press_brake",
    code: "WS-ABKANT-02",
    name: "CNC Abkant Büküm Tezgahı 175T",
    category: "machine",
    hourlyOperatingCost: 280,
    hourlyDepreciationCost: 190,
    standardCapacityHoursPerDay: 8,
    efficiencyRate: 0.88,
    status: "idle",
    assignedOperatorName: "Ali Vural",
    branchId: "br_1",
    branchName: "Merkez Fabrika / Üretim Tesisi",
    warehouseId: "wh_1",
    warehouseName: "Gebze Lojistik & Ana Depo",
    notes: "3 metre 175 Ton Hidrolik Hassas Büküm",
  },
  {
    id: "ws_welding",
    code: "WS-KAYNAK-03",
    name: "Robotik Gazaltı & TIG Kaynak İstasyonu",
    category: "machine",
    hourlyOperatingCost: 350,
    hourlyDepreciationCost: 220,
    standardCapacityHoursPerDay: 8,
    efficiencyRate: 0.85,
    status: "running",
    currentWorkOrderId: "wo_002",
    currentWorkOrderNumber: "WO-2026-00102",
    assignedOperatorName: "Hasan Çelik (Kaynak Uzmanı)",
    branchId: "br_1",
    branchName: "Merkez Fabrika / Üretim Tesisi",
  },
  {
    id: "ws_paint_booth",
    code: "WS-BOYA-04",
    name: "Elektrostatik Toz Boya & Fırınlama Hattı",
    category: "paint_booth",
    hourlyOperatingCost: 520,
    hourlyDepreciationCost: 280,
    standardCapacityHoursPerDay: 16,
    efficiencyRate: 0.90,
    status: "idle",
    assignedOperatorName: "Kemal Yılmaz",
    branchId: "br_1",
    branchName: "Merkez Fabrika / Üretim Tesisi",
  },
  {
    id: "ws_assembly_line",
    code: "WS-MONTAJ-05",
    name: "Ergonomik Masa & Koltuk Montaj Hattı",
    category: "assembly_line",
    hourlyOperatingCost: 220,
    hourlyDepreciationCost: 110,
    standardCapacityHoursPerDay: 8,
    efficiencyRate: 0.94,
    status: "running",
    currentWorkOrderId: "wo_003",
    currentWorkOrderNumber: "WO-2026-00103",
    assignedOperatorName: "Montaj Ekibi (4 Teknisyen)",
    branchId: "br_1",
    branchName: "Merkez Fabrika / Üretim Tesisi",
  },
  {
    id: "ws_qc_pack",
    code: "WS-KALITE-06",
    name: "Son Kontrol, Test & Ambalajlama İstasyonu",
    category: "quality_station",
    hourlyOperatingCost: 180,
    hourlyDepreciationCost: 90,
    standardCapacityHoursPerDay: 8,
    efficiencyRate: 0.96,
    status: "idle",
    assignedOperatorName: "Zeynep Arslan (Kalite Mühendisi)",
    branchId: "br_1",
    branchName: "Merkez Fabrika / Üretim Tesisi",
  },
];

export const initialRoutings: Routing[] = [
  {
    id: "rout_001",
    routingCode: "ROUT-KLT-PRO",
    name: "Ergonomik Yönetici Koltuğu Standart Rotası",
    productName: "Ergonomik Yönetici Koltuğu Pro",
    totalSetupMinutes: 45,
    totalRunMinutesPerUnit: 38,
    isActive: true,
    createdAt: "2026-01-10",
    steps: [
      {
        id: "step_10",
        sequence: 10,
        operationName: "Metal İskelet Lazer Kesim",
        workstationId: "ws_cnc_laser",
        workstationName: "Fiber Lazer Kesim & Punch CNC",
        workstationType: "internal",
        setupTimeMinutes: 15,
        runTimePerUnitMinutes: 8,
        requiresQualityInspection: false,
      },
      {
        id: "step_20",
        sequence: 20,
        operationName: "İskelet Robotik Kaynak",
        workstationId: "ws_welding",
        workstationName: "Robotik Gazaltı & TIG Kaynak İstasyonu",
        workstationType: "internal",
        setupTimeMinutes: 10,
        runTimePerUnitMinutes: 10,
        requiresQualityInspection: true,
      },
      {
        id: "step_30",
        sequence: 30,
        operationName: "Fason Elektrostatik Toz Boya",
        workstationId: "ws_paint_booth",
        workstationName: "Dış Tedarikçi Fason Boyahane",
        workstationType: "subcontractor",
        subcontractorContactId: "c2",
        subcontractorContactName: "Mega Metal San. ve Tic. Ltd. Şti.",
        subcontractorUnitCost: 140,
        setupTimeMinutes: 0,
        runTimePerUnitMinutes: 0,
        queueTimeMinutes: 1440,
        requiresQualityInspection: true,
      },
      {
        id: "step_40",
        sequence: 40,
        operationName: "Sünger Giydirme & Mekanizma Montajı",
        workstationId: "ws_assembly_line",
        workstationName: "Ergonomik Masa & Koltuk Montaj Hattı",
        workstationType: "internal",
        setupTimeMinutes: 10,
        runTimePerUnitMinutes: 15,
        requiresQualityInspection: false,
      },
      {
        id: "step_50",
        sequence: 50,
        operationName: "Yük Testi, Kalite Kontrol & Ambalaj",
        workstationId: "ws_qc_pack",
        workstationName: "Son Kontrol, Test & Ambalajlama İstasyonu",
        workstationType: "internal",
        setupTimeMinutes: 10,
        runTimePerUnitMinutes: 5,
        requiresQualityInspection: true,
      },
    ],
  },
  {
    id: "rout_002",
    routingCode: "ROUT-PANO-IND",
    name: "Endüstriyel Otomasyon Elektrik Panosu Rotası",
    productName: "Schneider Elektrik Şalter Panosu Modülü",
    totalSetupMinutes: 30,
    totalRunMinutesPerUnit: 55,
    isActive: true,
    createdAt: "2026-02-15",
    steps: [
      {
        id: "step_201",
        sequence: 10,
        operationName: "Sac Gövde Lazer Kesim & Havşalama",
        workstationId: "ws_cnc_laser",
        workstationName: "Fiber Lazer Kesim & Punch CNC",
        workstationType: "internal",
        setupTimeMinutes: 15,
        runTimePerUnitMinutes: 12,
        requiresQualityInspection: false,
      },
      {
        id: "step_202",
        sequence: 20,
        operationName: "CNC Abkant Büküm & Köşe Kaynağı",
        workstationId: "ws_press_brake",
        workstationName: "CNC Abkant Büküm Tezgahı 175T",
        workstationType: "internal",
        setupTimeMinutes: 15,
        runTimePerUnitMinutes: 18,
        requiresQualityInspection: true,
      },
      {
        id: "step_203",
        sequence: 30,
        operationName: "Elektrostatik RAL 7035 Toz Boya",
        workstationId: "ws_paint_booth",
        workstationName: "Elektrostatik Toz Boya & Fırınlama Hattı",
        workstationType: "internal",
        setupTimeMinutes: 20,
        runTimePerUnitMinutes: 10,
        requiresQualityInspection: true,
      },
      {
        id: "step_204",
        sequence: 40,
        operationName: "Şalt Malzeme Kablolama, Bara & Test",
        workstationId: "ws_assembly_line",
        workstationName: "Ergonomik Masa & Koltuk Montaj Hattı",
        workstationType: "internal",
        setupTimeMinutes: 0,
        runTimePerUnitMinutes: 25,
        requiresQualityInspection: true,
      },
    ],
  },
];

export const initialBillOfMaterials: BillOfMaterials[] = [
  {
    id: "bom_001",
    bomCode: "BOM-KLT-PRO-01",
    revision: 2,
    name: "Ergonomik Yönetici Koltuğu Pro Reçetesi",
    productId: "p_01_001",
    productCode: "STK-OCAK-001",
    productName: "Ergonomik Yönetici Koltuğu Pro (Siyah File)",
    category: "Mobilya & Ofis",
    outputQuantity: 1,
    outputUnit: "Adet",
    yieldRate: 0.98,
    routingId: "rout_001",
    routingName: "Ergonomik Yönetici Koltuğu Standart Rotası",
    laborHoursPerUnit: 0.65,
    laborHourlyRate: 240,
    overheadCostPerUnit: 85,
    isActive: true,
    isDefault: true,
    createdAt: "2026-01-10",
    updatedAt: "2026-07-20",
    description: "Multi-tilt senkron mekanizmalı, 3D hareketli kolçaklı ve alüminyum ayaklı lüks model.",
    items: [
      {
        id: "bomi_01",
        type: "raw_material",
        productId: "p_01_002",
        productCode: "HAM-MET-01",
        productName: "ST37 2mm Çelik Profil & İskelet Sacı",
        quantityPerUnit: 4.2,
        unit: "Kg",
        wasteRate: 0.05,
        unitCost: 65,
        notes: "Lazer kesim ve büküm için",
      },
      {
        id: "bomi_02",
        type: "semi_finished",
        productId: "p_01_003",
        productCode: "YMM-MEK-02",
        productName: "Senkron Çift Kollu Koltuk Mekanizması",
        quantityPerUnit: 1,
        unit: "Adet",
        wasteRate: 0.01,
        unitCost: 480,
      },
      {
        id: "bomi_03",
        type: "raw_material",
        productId: "p_01_004",
        productCode: "HAM-SNG-03",
        productName: "60 Dansite Poliüretan Dökme Sünger",
        quantityPerUnit: 1.8,
        unit: "Kg",
        wasteRate: 0.03,
        unitCost: 190,
      },
      {
        id: "bomi_04",
        type: "raw_material",
        productId: "p_01_005",
        productCode: "HAM-KMS-04",
        productName: "Nefes Alabilir Alev Almaz File Kumaş (Siyah)",
        quantityPerUnit: 1.4,
        unit: "Metre",
        wasteRate: 0.08,
        unitCost: 160,
      },
      {
        id: "bomi_05",
        type: "raw_material",
        productId: "p_01_006",
        productCode: "HAM-AMORT-05",
        productName: "Class 4 Ağır Hizmet Gazlı Amortisör",
        quantityPerUnit: 1,
        unit: "Adet",
        wasteRate: 0.01,
        unitCost: 220,
      },
      {
        id: "bomi_06",
        type: "packaging",
        productId: "p_01_007",
        productCode: "AMB-KUTU-06",
        productName: "Çift Oluklu Ağır Hizmet Koltuk Kolisi + Balonlu Naylon",
        quantityPerUnit: 1,
        unit: "Set",
        wasteRate: 0.02,
        unitCost: 75,
      },
    ],
  },
  {
    id: "bom_002",
    bomCode: "BOM-PANO-800",
    revision: 1,
    name: "Schneider Elektrik Şalter Panosu 800x600 Reçetesi",
    productId: "p_01_008",
    productCode: "STK-OCAK-008",
    productName: "Schneider Elektrik Şalter Panosu (IP65 Çelik)",
    category: "Otomasyon & Elektrik",
    outputQuantity: 1,
    outputUnit: "Set",
    yieldRate: 0.99,
    routingId: "rout_002",
    routingName: "Endüstriyel Otomasyon Elektrik Panosu Rotası",
    laborHoursPerUnit: 1.2,
    laborHourlyRate: 280,
    overheadCostPerUnit: 120,
    isActive: true,
    isDefault: true,
    createdAt: "2026-02-15",
    updatedAt: "2026-08-01",
    description: "IP65 sızdırmazlık contalı, fırın boyalı endüstriyel ana dağıtım panosu.",
    items: [
      {
        id: "bomi_201",
        type: "raw_material",
        productId: "p_01_009",
        productCode: "HAM-DKP-15",
        productName: "1.5mm DKP Çelik Sac Plaka (1000x2000)",
        quantityPerUnit: 18.5,
        unit: "Kg",
        wasteRate: 0.06,
        unitCost: 58,
      },
      {
        id: "bomi_202",
        type: "raw_material",
        productId: "p_01_010",
        productCode: "HAM-BOYA-RAL",
        productName: "Elektrostatik Toz Boya (RAL 7035 Açık Gri)",
        quantityPerUnit: 1.2,
        unit: "Kg",
        wasteRate: 0.12,
        unitCost: 140,
      },
      {
        id: "bomi_203",
        type: "semi_finished",
        productId: "p_01_011",
        productCode: "ELK-SALT-01",
        productName: "Schneider Compact NSX 250A Kompakt Şalter",
        quantityPerUnit: 1,
        unit: "Adet",
        wasteRate: 0.0,
        unitCost: 4200,
      },
      {
        id: "bomi_204",
        type: "consumable",
        productId: "p_01_012",
        productCode: "SARF-BAKIR-01",
        productName: "Elektrolitik Bakır Bara 30x5 (Topraklama & Faz)",
        quantityPerUnit: 3.5,
        unit: "Kg",
        wasteRate: 0.04,
        unitCost: 480,
      },
    ],
  },
];

export const initialWorkOrders: WorkOrder[] = [
  {
    id: "wo_001",
    orderNumber: "WO-2026-00101",
    originType: "sales_order",
    sourceSalesOrderId: "ord_001",
    sourceSalesOrderNumber: "SIP-2026-00084",
    customerName: "TeknoHolding A.Ş.",
    productId: "p_01_001",
    productCode: "STK-OCAK-001",
    productName: "Ergonomik Yönetici Koltuğu Pro (Siyah File)",
    bomId: "bom_001",
    bomCode: "BOM-KLT-PRO-01",
    routingId: "rout_001",
    lotNumber: "LOT2608-KLT-01",
    barcode: "WO260800101",
    plannedQuantity: 50,
    producedQuantity: 32,
    scrappedQuantity: 1,
    unit: "Adet",
    sourceWarehouseId: "wh_1",
    sourceWarehouseName: "Gebze Lojistik & Ana Depo",
    targetWarehouseId: "wh_1",
    targetWarehouseName: "Gebze Lojistik & Ana Depo",
    status: "in_progress",
    priority: "high",
    plannedStartDate: "2026-08-25",
    plannedDueDate: "2026-08-30",
    actualStartDate: "2026-08-25 08:30",
    isMaterialIssued: true,
    isFinishedGoodReceived: false,
    createdAt: "2026-08-24",
    updatedAt: "2026-08-27",
    notes: "TeknoHolding yeni genel müdürlük katı projesi için acil teslimat.",
    costBreakdown: {
      rawMaterialCost: 71800,
      laborCost: 7800,
      machineDepreciationCost: 4900,
      subcontractorCost: 7000,
      overheadCost: 4250,
      totalCost: 95750,
      unitCost: 1915,
    },
    operations: [
      {
        id: "wo_op_1",
        sequence: 10,
        operationName: "Metal İskelet Lazer Kesim",
        workstationId: "ws_cnc_laser",
        workstationName: "Fiber Lazer Kesim & Punch CNC",
        workstationType: "internal",
        status: "completed",
        plannedDurationMinutes: 415,
        actualDurationMinutes: 390,
        actualStartTime: "2026-08-25 08:45",
        actualEndTime: "2026-08-25 15:15",
        operatorName: "Murat Demir",
        producedQuantity: 50,
        scrappedQuantity: 1,
        qualityApproval: {
          approvedBy: "Zeynep Arslan",
          approvedAt: "2026-08-25 15:30",
          status: "approved",
        },
      },
      {
        id: "wo_op_2",
        sequence: 20,
        operationName: "İskelet Robotik Kaynak",
        workstationId: "ws_welding",
        workstationName: "Robotik Gazaltı & TIG Kaynak İstasyonu",
        workstationType: "internal",
        status: "completed",
        plannedDurationMinutes: 510,
        actualDurationMinutes: 480,
        actualStartTime: "2026-08-26 08:30",
        actualEndTime: "2026-08-26 16:30",
        operatorName: "Hasan Çelik",
        producedQuantity: 49,
        scrappedQuantity: 0,
        qualityApproval: {
          approvedBy: "Zeynep Arslan",
          approvedAt: "2026-08-26 17:00",
          status: "approved",
        },
      },
      {
        id: "wo_op_3",
        sequence: 30,
        operationName: "Fason Elektrostatik Toz Boya",
        workstationId: "ws_paint_booth",
        workstationName: "Dış Tedarikçi Fason Boyahane",
        workstationType: "subcontractor",
        subcontractorContactId: "c2",
        subcontractorContactName: "Mega Metal San. ve Tic. Ltd. Şti.",
        status: "completed",
        plannedDurationMinutes: 1440,
        actualDurationMinutes: 1320,
        actualStartTime: "2026-08-26 17:30",
        actualEndTime: "2026-08-27 15:30",
        producedQuantity: 49,
        scrappedQuantity: 0,
      },
      {
        id: "wo_op_4",
        sequence: 40,
        operationName: "Sünger Giydirme & Mekanizma Montajı",
        workstationId: "ws_assembly_line",
        workstationName: "Ergonomik Masa & Koltuk Montaj Hattı",
        workstationType: "internal",
        status: "in_progress",
        plannedDurationMinutes: 760,
        actualDurationMinutes: 420,
        actualStartTime: "2026-08-27 08:30",
        operatorName: "Montaj Ekibi",
        producedQuantity: 32,
        scrappedQuantity: 0,
      },
      {
        id: "wo_op_5",
        sequence: 50,
        operationName: "Yük Testi, Kalite Kontrol & Ambalaj",
        workstationId: "ws_qc_pack",
        workstationName: "Son Kontrol, Test & Ambalajlama İstasyonu",
        workstationType: "internal",
        status: "pending",
        plannedDurationMinutes: 260,
        actualDurationMinutes: 0,
        producedQuantity: 0,
        scrappedQuantity: 0,
      },
    ],
    allocatedMaterials: [
      {
        id: "wom_01",
        productId: "p_01_002",
        productCode: "HAM-MET-01",
        productName: "ST37 2mm Çelik Profil & İskelet Sacı",
        type: "raw_material",
        plannedQuantity: 210,
        allocatedQuantity: 210,
        consumedQuantity: 212,
        unit: "Kg",
        unitCost: 65,
        totalCost: 13780,
      },
      {
        id: "wom_02",
        productId: "p_01_003",
        productCode: "YMM-MEK-02",
        productName: "Senkron Çift Kollu Koltuk Mekanizması",
        type: "semi_finished",
        plannedQuantity: 50,
        allocatedQuantity: 50,
        consumedQuantity: 32,
        unit: "Adet",
        unitCost: 480,
        totalCost: 24000,
      },
      {
        id: "wom_03",
        productId: "p_01_004",
        productCode: "HAM-SNG-03",
        productName: "60 Dansite Poliüretan Dökme Sünger",
        type: "raw_material",
        plannedQuantity: 90,
        allocatedQuantity: 90,
        consumedQuantity: 58,
        unit: "Kg",
        unitCost: 190,
        totalCost: 17100,
      },
      {
        id: "wom_04",
        productId: "p_01_005",
        productCode: "HAM-KMS-04",
        productName: "Nefes Alabilir Alev Almaz File Kumaş (Siyah)",
        type: "raw_material",
        plannedQuantity: 70,
        allocatedQuantity: 70,
        consumedQuantity: 45,
        unit: "Metre",
        unitCost: 160,
        totalCost: 11200,
      },
    ],
  },
  {
    id: "wo_002",
    orderNumber: "WO-2026-00102",
    originType: "manual_stock",
    productId: "p_01_008",
    productCode: "STK-OCAK-008",
    productName: "Schneider Elektrik Şalter Panosu (IP65 Çelik)",
    bomId: "bom_002",
    bomCode: "BOM-PANO-800",
    routingId: "rout_002",
    lotNumber: "LOT2608-PANO-02",
    barcode: "WO260800102",
    plannedQuantity: 20,
    producedQuantity: 0,
    scrappedQuantity: 0,
    unit: "Set",
    sourceWarehouseId: "wh_1",
    sourceWarehouseName: "Gebze Lojistik & Ana Depo",
    targetWarehouseId: "wh_1",
    targetWarehouseName: "Gebze Lojistik & Ana Depo",
    status: "planned",
    priority: "medium",
    plannedStartDate: "2026-08-28",
    plannedDueDate: "2026-09-05",
    isMaterialIssued: false,
    isFinishedGoodReceived: false,
    createdAt: "2026-08-26",
    updatedAt: "2026-08-26",
    notes: "Stok tamamlama için 20 adet standart dağıtım panosu üretimi.",
    costBreakdown: {
      rawMaterialCost: 149400,
      laborCost: 6720,
      machineDepreciationCost: 3840,
      subcontractorCost: 0,
      overheadCost: 2400,
      totalCost: 162360,
      unitCost: 8118,
    },
    operations: [],
    allocatedMaterials: [],
  },
  {
    id: "wo_003",
    orderNumber: "WO-2026-00095",
    originType: "sales_order",
    sourceSalesOrderId: "ord_003",
    sourceSalesOrderNumber: "SIP-2026-00079",
    customerName: "Anadolu İnşaat A.Ş.",
    productId: "p_01_001",
    productCode: "STK-OCAK-001",
    productName: "Ergonomik Yönetici Koltuğu Pro (Siyah File)",
    bomId: "bom_001",
    bomCode: "BOM-KLT-PRO-01",
    routingId: "rout_001",
    lotNumber: "LOT2608-KLT-95",
    barcode: "WO260800095",
    plannedQuantity: 40,
    producedQuantity: 40,
    scrappedQuantity: 0,
    unit: "Adet",
    sourceWarehouseId: "wh_1",
    sourceWarehouseName: "Gebze Lojistik & Ana Depo",
    targetWarehouseId: "wh_1",
    targetWarehouseName: "Gebze Lojistik & Ana Depo",
    status: "completed",
    priority: "urgent",
    plannedStartDate: "2026-08-15",
    plannedDueDate: "2026-08-22",
    actualStartDate: "2026-08-15 09:00",
    actualEndDate: "2026-08-21 17:00",
    isMaterialIssued: true,
    isFinishedGoodReceived: true,
    createdAt: "2026-08-14",
    updatedAt: "2026-08-22",
    notes: "Başarıyla tamamlandı ve depoya teslim edildi.",
    costBreakdown: {
      rawMaterialCost: 57440,
      laborCost: 6240,
      machineDepreciationCost: 3920,
      subcontractorCost: 5600,
      overheadCost: 3400,
      totalCost: 76600,
      unitCost: 1915,
    },
    operations: [],
    allocatedMaterials: [],
  },
];

export const initialSubcontractOrders: SubcontractOrder[] = [
  {
    id: "sub_001",
    dispatchNo: "FAS-IRS-2026-0042",
    workOrderId: "wo_001",
    workOrderNumber: "WO-2026-00101",
    operationId: "wo_op_3",
    operationName: "Fason Elektrostatik Toz Boya",
    subcontractorContactId: "c2",
    subcontractorContactName: "Mega Metal San. ve Tic. Ltd. Şti.",
    productId: "p_01_001",
    productName: "Ergonomik Koltuk İskeleti (Kaynaklı Ham)",
    quantity: 50,
    unit: "Adet",
    unitPrice: 140,
    totalPrice: 7000,
    dispatchDate: "2026-08-26",
    expectedReturnDate: "2026-08-28",
    actualReturnDate: "2026-08-27",
    status: "completed",
    receivedQuantity: 50,
    scrapQuantity: 0,
    serviceInvoiceNo: "MEG20260000089",
    notes: "RAL 9005 Mat Siyah Toz Boya işlemi yapıldı.",
    createdAt: "2026-08-26",
  },
];


